import streamlit as st
import streamlit.components.v1 as components
import time
from base64 import b64encode
from pathlib import Path
import plotly.graph_objects as go
import plotly.io as pio
import numpy as np
from src.synthetic_data import DemoScenario, draw_sample
from src.estimators import location_estimates
from src.mini_ga import MiniGAConfig, run_pedagogical_ga
from src import simplex as simplex_renderer
from src.fixed_simplex import fixed_simplex_figure
from src.simplex_svg import simplex_svg
from src.cluster_evolution import cluster_map_svg, contamination_shift_svg
from src.experiment_pipeline import STAGES as PIPELINE_STAGES, experiment_pipeline_svg
from src.defense_mode import VALIDATION_STAGES, defense_scene_svg, validation_scene_svg
from src.research_logic import PANELS as RESEARCH_PANELS, research_logic_svg
from src.data_loader import load_winners, load_final_decisions, load_bootstrap_ci, load_evidence_taxonomy, load_validated_specialists, load_dirichlet_summary, load_dirichlet_signals
from src.constants import ESTIMATOR_NAMES

UNIVERSITY_LOGO_DATA_URI = (
    "data:image/jpeg;base64,"
    + b64encode((Path(__file__).parent / "assets" / "university_of_hull_logo.jpeg").read_bytes()).decode("ascii")
)

# Presenter notes are a rehearsal aid, not a source of new thesis claims.  Each
# entry below is condensed from the defense deck and the written thesis.
PRESENTER_NOTES = {
    "cover": ("Opening", "Defense deck · title slide", [
        "Introduce the problem in one sentence: we want better estimates of a population mean when ordinary conditions fail.",
        "State the bounded contribution: this is benchmark-gated, regime-conditional discovery — not a claim that a GA is universally superior.",
    ], "Move to the research logic: why this experiment is necessary."),
    "research_problem": ("Layer 1 · Problem", "Defense deck · 01 Research framing", [
        ("HELP", "The problem is this: no estimator is uniformly reliable when the conditions of the data change, especially under contamination. With clean, approximately symmetric data and moderate tails, the sample mean uses every observation efficiently and is usually close to the target. But when a small number of observations are extreme, or the distribution is strongly skewed, those observations can pull the mean away from the population mean. Robust estimators reduce the influence of those observations, although that protection can cost efficiency when the data are clean. So the ranking is conditional on the regime, not universal."),
        ("FORMULAS AND NOTATION", ["Formula: R = {family, n, γ, scale, mechanism}", "family = distributional shape.", "n = sample size.", "γ = proportion of contaminated observations.", "scale = severity of contamination.", "mechanism = where or how contamination enters the sample.", "Formula: x ∼ R", "x = one observed sample.", "∼ = ‘is generated from’. R = the complete regime that generated the sample.", "Formula: R(T, R) = E[(T(x) − θ)² | R]", "T = the estimator being evaluated.", "θ = the true population mean.", "E[·] = expected value over repeated samples.", "(T(x) − θ)² = squared estimation error.", "| R = conditional on the specified regime."]),
        ("POSSIBLE QUESTIONS", [("Why not use the mean everywhere?", "Its clean-data efficiency does not make it uniformly reliable under skewness, heavy tails or contamination."), ("Why condition on R?", "Averaging across incompatible data-generating conditions can hide the setting in which an estimator fails.")]),
    ], "Therefore the question is not ‘which estimator always wins?’ but ‘under which regimes can improvement be justified?’"),
    "research_objective": ("Layer 1 · Objective / research questions", "Defense deck · 01 Research framing; thesis abstract", [
        ("HELP", "The objective is not to crown a universal genetic-algorithm estimator. It is to build a benchmark-gated framework for estimating the population mean E[X] under controlled regimes. The GA is used as a search tool: it proposes an interpretable mixture of established estimators. A proposal is then frozen and challenged with new seeds, stronger benchmarks and related regimes. The four research questions make that programme explicit: where can a composite first improve; do gains remain after selection; what changes when the estimator library expands; and do supported specialists transfer beyond their discovery setting?"),
        ("FORMULAS AND NOTATION", ["Programme: R → x → {T₁(x), …, Tᴸ(x)} → w → gate.", "R = data-generating regime.", "x = sample drawn from that regime.", "T₁(x), …, Tᴸ(x) = admissible base estimators applied to x.", "L = number of estimators in the bank.", "w = vector of mixture weights.", "gate = decision rule that decides whether evidence supports replacing the best benchmark.", "Formula: θ = E[X]", "X = random variable generated by the population distribution.", "E[X] = expectation of X; the population mean θ.", "freeze(w) = keep learned weights fixed for confirmation; do not retrain on validation data."]),
        ("POSSIBLE QUESTIONS", [("Why use a GA rather than select one estimator?", "It explores transparent convex combinations while retaining named components."), ("Why is the gate necessary?", "Optimisation can overfit a discovery setting; the gate separates a promising candidate from a supported claim."), ("What is success?", "Either a supported specialist or a justified decision to retain the benchmark.")]),
    ], "Before looking at results, make the predictions explicit."),
    "research_hypotheses": ("Layer 1 · H1–H4", "Defense deck · 01 Research framing", [
        ("HELP", "These four hypotheses are one reasoning chain rather than four separate claims. H1 says there is no universal estimator. H2 says estimator performance therefore depends on the regime. H3 says a GA mixture may help, but only in selected regimes where the trade-off is favourable. H4 protects the conclusion: the benchmark gate prevents us from turning every discovery signal into a claim. The expected result is selective improvement and many valid benchmark-retained cases."),
        ("FORMULAS AND NOTATION", ["Hypothesis chain: H1 → H2 → H3 → H4.", "H1 = no universal estimator.", "H2 = conditional risk changes with R.", "H3 = a GA composite may help selectively.", "H4 = the benchmark gate controls acceptance.", "Formula: e² = (θ̂(x) − θ)²", "θ̂(x) = estimate calculated from sample x.", "θ = true population mean.", "e² = squared error for one replication.", "Formula: MSE = average of e² across replications.", "q95 MSE = 95th-percentile boundary of the replicate-level squared-error distribution."]),
        ("POSSIBLE QUESTIONS", [("Is H3 a claim that GA should win often?", "No. It predicts selected, regime-specific opportunity."), ("Does retaining a benchmark reject the whole study?", "No. It is the correct output when evidence does not support replacement."), ("Why pre-specify H4?", "It prevents hindsight interpretation of an optimisation result as a general discovery.")]),
    ], "Now define exactly what is fixed and what the GA is allowed to change."),
    "research_target": ("Layer 1 · Target / simplex", "Defense deck · 01 Research framing; thesis abstract", [
        ("HELP", "Here I separate the target from the estimator. The target is fixed: θ = E[X], the population mean defined by the simulated distribution. The GA never changes θ. It only searches a recipe for estimating it, built from an admissible bank of base estimators. Because the weights are non-negative and add to one, every candidate is an interpretable convex mixture rather than an opaque prediction. This makes the recipe inspectable and keeps the search inside the probability simplex."),
        ("FORMULAS AND NOTATION", ["Formula: θ = E[X]", "θ = true population mean and fixed target.", "X = random variable from the data-generating distribution.", "E[X] = expectation, or population mean, of X.", "Formula: θ̂GA(x) = Σⱼ₌₁ᴸ wⱼTⱼ(x)", "θ̂GA(x) = GA composite estimate for sample x.", "Tⱼ(x) = jth base estimator applied to x.", "wⱼ = weight given to the jth estimator.", "L = number of components in the estimator bank.", "Σ = sum over all components.", "Simplex constraint: wⱼ ≥ 0 and Σⱼ₌₁ᴸwⱼ = 1.", "wⱼ ≥ 0 = no negative contribution.", "Σwⱼ = 1 = weights are proportions summing to 100%.", "Admissibility = the estimator must be defined on the data support; geometric and harmonic means require positive values."]),
        ("POSSIBLE QUESTIONS", [("Why insist on non-negative weights?", "They preserve an interpretable mixture and avoid arbitrary negative extrapolation."), ("Why not let the GA estimate θ directly?", "The aim is an auditable combination of established estimators, not a black-box predictor."), ("Does a valid simplex vector guarantee better performance?", "No. Validity is separate from evidence of lower conditional risk.")]),
    ], "A valid mixture can still lose; next is the condition under which it could improve."),
    "research_why_win": ("Layer 1 · Why a composite can win", "Thesis · finite-sample bias, variance and MSE; defense deck", [
        ("HELP", "A composite can only win through a favourable bias–variance trade-off. The sample mean has no general competitor advantage under clean Normal data because it is already highly efficient. But in skewed, heavy-tailed or contaminated regimes, a mixture can down-weight estimators that react strongly to extremes and combine robust components in a way that reduces sampling variability. That helps only if the variance reduction is larger than the squared bias introduced by moving away from the mean. Monte Carlo measures this; the benchmark gate decides whether the gain is credible."),
        ("FORMULAS AND NOTATION", ["Formula: MSE(θ̂) = Bias(θ̂)² + Var(θ̂)", "θ̂ = estimator being evaluated.", "MSE = mean squared error.", "Bias(θ̂) = systematic difference between the estimator’s average value and θ.", "Var(θ̂) = sampling variability of the estimator.", "Formula: Bias(θ̂GA)² + Var(θ̂GA) < Var(X̄)", "θ̂GA = composite GA estimator.", "X̄ = sample mean.", "< = the composite must have lower total expected squared error.", "Formula: e² = (θ̂(x) − θ)²", "e² = squared error for one replication.", "Formula: q95 MSE = 95th percentile of the replicate-level squared-error distribution.", "q95 MSE = upper-tail protection against difficult cases, not merely average performance."]),
        ("POSSIBLE QUESTIONS", [("Why not minimise MSE alone?", "A method could improve on average while producing unacceptable difficult-case errors; q95 adds upper-tail protection."), ("Is bias always bad?", "No. A small bias can be worthwhile if it buys a larger reduction in variance, but the trade-off is measured against the same target."), ("Why is clean Normal data important?", "It is the difficult baseline for improvement because the mean is already efficient there.")]),
    ], "Simulation lets us measure that trade-off against known truth."),
    "data_world": ("Layer 2 · Data-generating world", "Defense deck · Monte Carlo evaluation; Appendix A1/A2", [
        "Simulation is deliberate because it makes the true target known; real datasets do not reveal the population mean.",
        "The grid varies family, sample size, contamination rate, outlier scale and contamination mechanism to stress estimator failure modes.",
        "The simulator is validated before any GA conclusion is trusted.",
    ], "With a controlled world and known θ, Monte Carlo can measure true error."),
    "monte_carlo_engine": ("Layer 3 · Monte Carlo measurement engine", "Defense deck · 05 Monte Carlo evaluation", [
        "Specify one regime R, compute θ = E[X], generate repeated samples, and apply every estimator to the same sample paths.",
        "For each replication, calculate (Tj(x(r)) − θ)². Aggregate to MSE and q95 MSE.",
        "The GA does not create the target; it searches using certified error estimates from this procedure.",
    ], "The next question is whether the simulated world itself behaves as designed."),
    "monte_carlo_validation_0": ("Layer 3 · Validation: moment fidelity", "Defense deck · Appendix A1", [
        "Check that large generated populations recover their analytic moments before scoring estimators.",
        "If the population target is wrong at this stage, every subsequent error calculation is wrong.",
    ], "Proceed to validate the contamination design."),
    "monte_carlo_validation_1": ("Layer 3 · Validation: contamination fidelity", "Defense deck · Monte Carlo workflow", [
        "Verify that the realised contamination rate and severity match the regime label after injection.",
        "A declared upper-tail or 10% contamination regime must behave as labelled before it enters the experiment.",
    ], "Then check a known statistical benchmark."),
    "monte_carlo_validation_2": ("Layer 3 · Validation: statistical sanity", "Defense deck · Appendix A1", [
        "Under clean Normal data, the sample mean should outperform the median in MSE; this is a theory-based sanity check.",
        "Recovering this ordering supports the fitness and error calculations, but does not yet prove a GA result.",
    ], "Finally, connect the synthetic grid to relevant empirical shapes."),
    "monte_carlo_validation_3": ("Layer 3 · Validation: empirical anchoring", "Thesis abstract; defense deck · Appendix A1", [
        "Public-data diagnostics are used to check that synthetic worlds cover relevant shapes of interest.",
        "This is calibration, not known-θ validation: real data do not provide population ground truth.",
    ], "Only after these checks is the search procedure interpreted."),
    "simulation_lab": ("Layer 4 · Simulation lab", "Defense script map", [
        "Change contamination and observe estimator movement. Keep the message simple: estimator ranking depends on the regime.",
        "This is a deterministic pedagogical demonstration, not a rerun of the thesis search.",
    ], "Next, show how a candidate mixture is searched on the simplex."),
    "ga_search": ("Layer 5 · GA search", "Defense deck · 05 Genetic Algorithm Search", [
        "The GA receives certified error information and an admissible estimator bank, then initializes valid simplex weight vectors.",
        "Selection, crossover, mutation and elitism propose a candidate specialist; they do not establish a final claim.",
        "Held-out evidence decides: if the gate is insufficient, the benchmark remains the final answer.",
    ], "The pipeline makes that distinction between proposal and evidence explicit."),
    "pipeline": ("Layer 6 · Experiment pipeline", "Defense script map; thesis abstract", [
        "Narrate the sequence: discovery proposes candidates; weights are frozen; new seeds and stronger benchmarks test credibility.",
        "Keep discovery, fixed-weight confirmation, profile audit and external calibration distinct.",
    ], "Now inspect the precomputed thesis evidence, not a live optimization."),
    "results": ("Layer 7 · Results journey", "Defense deck · Results: strict validation and transfer/audit", [
        "Use the selected result stage to make a bounded claim. Stronger validation narrows broad discovery signals to local specialists.",
        "The essential conclusion is evidence conditional on profile, not a universal GA winner.",
    ], "Technical drill-down shows the candidate-level evidence behind that claim."),
    "technical": ("Layer 8 · Technical drill-down", "Thesis abstract; defense deck · strict validation", [
        "Read the displayed decision as fixed-weight evidence; do not treat a discovery pass as confirmation.",
        "Bootstrap intervals, unseen-similar regimes and evidence taxonomy constrain the interpretation.",
    ], "Finish with the contribution and its limits."),
    "conclusions": ("Layer 9 · Conclusions", "Defense script map · closing message", [
        "The GA proposes candidate mixtures; held-out and fixed-weight evidence decides what survives.",
        "The contribution is an auditable way to identify conditional opportunity and retain the benchmark when support is insufficient.",
    ], "Invite questions on the simulation, gate, validation or transfer evidence."),
}

_query = st.query_params
_browser_note = PRESENTER_NOTES.get(_query.get("section", "")) if _query.get("presenter_notes") == "1" else None
st.set_page_config(page_title=_browser_note[0] if _browser_note else "Robust Estimators Lab", page_icon="📊", layout="wide")
pio.templates.default = "plotly_dark"
st.markdown("""<style>
.stApp{background:radial-gradient(circle at 48% -12%,#16365c 0,#08172a 35%,#040a14 76%)!important;color:#eef5ff}.block-container{padding:.45rem 2rem 3rem!important;max-width:none!important}.stMetric{background:linear-gradient(135deg,#0d2038,#081525)!important;border:1px solid #218dca!important;border-top:3px solid #9a5cff!important;border-radius:7px;padding:10px;box-shadow:inset 0 0 18px rgba(33,141,202,.08)}.stMetric label,.stMetric [data-testid="stMetricLabel"]{color:#b8c8de!important}.stMetric [data-testid="stMetricValue"]{color:#f5f8ff!important}.badge{padding:6px 10px;border-radius:6px;font-size:.78rem;font-weight:800;display:inline-block;letter-spacing:.03em}.demo{background:#28184c;color:#d7c3ff;border:1px solid #8759de}.thesis{background:#0b372d;color:#9df0b7;border:1px solid #3aaf6f}
h1{color:#f5f8ff!important;margin:0 0 .1rem!important;font-size:2rem!important;text-shadow:0 0 18px rgba(71,169,255,.34)}h2,h3{color:#f2f7ff!important}[data-testid="stCaptionContainer"],.stCaption{color:#aebed3!important}[data-baseweb="tab-list"]{border-bottom:1px solid #2374b4!important;box-shadow:none!important;margin-top:.25rem!important;gap:.4rem}[data-baseweb="tab-border"]{display:none!important}[data-testid="stTabs"]>div:first-child{border-bottom:0!important}[data-baseweb="tab"]{color:#aebed3!important;background:#0a1930!important;border:1px solid #1d5688!important;border-bottom:0!important;border-radius:6px 6px 0 0!important;font-weight:700!important}[aria-selected="true"][data-baseweb="tab"]{color:#f6fbff!important;background:#102a49!important;box-shadow:inset 0 2px #4fc3ff!important}.layer-heading{font-size:1.3rem;font-weight:800;color:#f5f8ff;margin:.3rem 0 .1rem;text-shadow:0 0 14px rgba(79,195,255,.25)}.layer-subheading{color:#aebed3;margin:0 0 .75rem}.scenario-panel{border:1px solid #237fc0;border-left:4px solid #4fc3ff;border-radius:7px;background:linear-gradient(135deg,#0e2743,#081626);padding:.8rem 1rem;margin:.45rem 0 .8rem;color:#e8f3ff}.independent-note{color:#aebed3;font-size:.86rem;border-top:1px solid #20517e;padding-top:.65rem;margin-top:.35rem}.metric-caption{font-size:.78rem;color:#aebed3;margin-top:-.4rem}
div[data-testid="stVerticalBlockBorderWrapper"],div[data-testid="stExpander"]{border-color:#236b9e!important;background:#08182b!important}.stButton>button{background:linear-gradient(135deg,#5931bd,#2575bb)!important;color:#fff!important;border:1px solid #62c7ff!important;border-radius:6px!important;font-weight:700}.stSelectbox label,.stSlider label,.stNumberInput label,.stRadio label{color:#dceaff!important}.stAlert{background:#102a49!important;border:1px solid #287db5!important;color:#e7f4ff!important}.js-plotly-plot .plotly .modebar{background:#102541!important}
.pipeline-stage{min-height:136px;padding:14px 12px;border:1px solid #2b668f;border-radius:9px;background:#0a1b30;color:#b9cae0}.pipeline-stage.active{background:linear-gradient(135deg,#203d67,#152b48);border:2px solid #f3c743;box-shadow:0 0 20px rgba(243,199,67,.22);color:#f6fbff}.pipeline-step{font-size:11px;font-weight:800;letter-spacing:.08em;color:#72cfff}.pipeline-title{font-size:16px;font-weight:800;margin:8px 0}.pipeline-mini{font-size:12px;line-height:1.35}.story-panel{min-height:245px;padding:24px;border:1px solid #367eaf;border-radius:10px;background:linear-gradient(135deg,#0d2642,#08182b)}.story-kicker{font-size:12px;font-weight:800;letter-spacing:.1em;color:#72cfff}.story-title{font-size:28px;font-weight:800;color:#f5f8ff;margin:8px 0 16px}.story-label{font-size:12px;font-weight:800;letter-spacing:.08em;color:#f3c743;margin-bottom:6px}.story-body{font-size:16px;line-height:1.48;color:#dbe9f7}.funnel-step{padding:10px 14px;margin:6px auto;border:1px solid #3c79a5;border-radius:6px;background:#0d2642;color:#dceaff;text-align:center;font-weight:700}.funnel-step.active{border-color:#4de080;color:#c8ffd7;background:#123d30}
[data-testid="stSidebar"]{min-width:215px!important;max-width:215px!important;background:#071525!important;border-right:1px solid #245f8e}[data-testid="stSidebar"] [data-testid="stRadio"] label{font-size:.78rem!important;line-height:1.15!important;padding:.18rem 0!important}
</style>""", unsafe_allow_html=True)

# The presenter view deliberately uses the same deployment, but it is rendered
# in a separate browser tab. The first two layers are a controlled preview of
# the workflow before notes are written for the whole defense.
if _query.get("presenter_notes") == "1":
    note_section = _query.get("section", "")
    note = PRESENTER_NOTES.get(note_section)
    if note:
        _heading, _source, talking_points, _transition = note
        def _render_presenter_section(label, copy):
            if label == "FORMULAS AND NOTATION":
                content = "".join(f"<li>{item}</li>" for item in copy)
                return f'<section class="presenter-section"><h2>{label}</h2><ul>{content}</ul></section>'
            if label == "POSSIBLE QUESTIONS":
                content = "".join(f"<li>{question}<ul><li>{answer}</li></ul></li>" for question, answer in copy)
                return f'<section class="presenter-section"><h2>{label}</h2><ul>{content}</ul></section>'
            return f'<section class="presenter-section"><h2>{label}</h2><p>{copy}</p></section>'

        notes_html = "".join(_render_presenter_section(label, copy) for label, copy in talking_points)
        st.markdown(f'''<style>
          [data-testid="stAppViewContainer"]{{background:#071525!important}}
          .block-container{{max-width:1200px!important;padding:2.4rem 3.2rem!important}}
          .presenter-heading{{font-family:Arial,sans-serif;font-size:2rem;font-weight:800;line-height:1.2;color:#72cfff;margin:0 0 2.2rem}}
          .presenter-copy{{font-family:Arial,sans-serif;font-size:1.4rem;line-height:1.58;color:#f4f8ff}}
          .presenter-section{{margin:0 0 2.5rem}}
          .presenter-section h2{{font-size:1.05rem!important;letter-spacing:.12em;color:#72cfff!important;margin:0 0 .8rem!important}}
          .presenter-section p{{margin:0}}
          .presenter-section ul{{margin:.1rem 0 0 1.35rem;padding:0}}
          .presenter-section li{{margin:0 0 .7rem;padding-left:.15rem}}
          .presenter-section li ul{{margin:.45rem 0 .2rem 1.4rem;color:#bcd0e5}}
        </style><div class="presenter-heading">{_heading}</div><div class="presenter-copy">{notes_html}</div>''', unsafe_allow_html=True)
    else:
        st.warning("No hay notas configuradas para esta vista todavía.")
    st.stop()

st.title("Robust Estimators Lab")
st.caption("Defense Mode · a visual thesis narrative for robust estimator mixtures")

# Deliberate guardrail from the defense redesign: these two live demonstrations
# are approved teaching components. Do not change their visuals, data logic,
# controls, or playback except for navigation and truly global styling.
FROZEN_COMPONENTS = ("Layer 6 · Build the problem", "Layer 7 · GA search")

@st.cache_data(show_spinner="Building the pedagogical GA landscape…")
def build_layer2_demo(family, contamination, contamination_rate, outlier_scale, mutation_rate, population_size, lens, seed, renderer_version):
    """The terrain and GA share one artificial objective, changed by UI controls."""
    terrain = simplex_renderer.teaching_terrain(family, contamination, contamination_rate, outlier_scale, 0., lens)
    objective = lambda weights: simplex_renderer.demo_objective(weights[:, 0], weights[:, 1], weights[:, 2], terrain)
    # Eight real generations keep the defense animation concise while allowing
    # every generation to dwell on its five recorded GA operations.
    run = run_pedagogical_ga(objective, MiniGAConfig(population_size=population_size, generations=8, mutation_rate=mutation_rate, seed=seed))
    return {"run": run, "terrain": terrain}

DEFENSE_INDEX = (
    "00 · Cover", "01 · Research logic", "02 · Data-generating world", "03 · Monte Carlo engine",
    "04 · Simulation lab", "05 · GA search", "06 · Experiment pipeline", "07 · Results journey",
    "08 · Technical drill-down", "09 · Conclusions",
)

def _navigate(index):
    st.session_state.defense_section = DEFENSE_INDEX[max(0, min(index, len(DEFENSE_INDEX) - 1))]


def _set_presenter_state(key, value):
    """Set a view before the sidebar is rendered during Streamlit's rerun."""
    st.session_state[key] = value


def _presenter_note_key(active_section: str) -> str:
    """Resolve the exact speaking note for the currently visible defense view."""
    fixed = {
        "00 · Cover": "cover", "02 · Data-generating world": "data_world",
        "04 · Simulation lab": "simulation_lab", "05 · GA search": "ga_search",
        "06 · Experiment pipeline": "pipeline", "07 · Results journey": "results",
        "08 · Technical drill-down": "technical", "09 · Conclusions": "conclusions",
    }
    if active_section == "01 · Research logic":
        keys = ("research_problem", "research_objective", "research_hypotheses", "research_target", "research_why_win")
        return keys[int(st.session_state.get("research_panel", 0))]
    if active_section == "03 · Monte Carlo engine":
        if st.session_state.get("monte_carlo_view", "engine") == "validation":
            return f"monte_carlo_validation_{int(st.session_state.get('validation_stage', 0))}"
        return "monte_carlo_engine"
    return fixed[active_section]


def _presenter_notes_link(section: str) -> str:
    """Open and then reuse one movable presenter-notes browser window."""
    return f'''<a href="?presenter_notes=1&amp;section={section}"
        title="Open presenter notes in the presenter window" style="display:block;margin-top:1.4rem"
        onclick="const n=window.open(this.href, 'robust_estimators_presenter_notes', 'popup=yes,width=980,height=780,resizable=yes,scrollbars=yes'); if(n){{n.focus();}} return false;">
      <img src="{UNIVERSITY_LOGO_DATA_URI}" alt="University of Hull"
           style="display:block;width:100%;box-sizing:border-box;border-radius:6px;border:1px solid #245f8e;padding:4px;background:#fff" />
    </a>'''

with st.sidebar:
    st.markdown("### DEFENSE MODE")
    st.caption("Manual presentation index · live layers are preserved")
    active_section = st.radio("Defense section", DEFENSE_INDEX, label_visibility="collapsed", key="defense_section")
    position = DEFENSE_INDEX.index(active_section)
    previous, following = st.columns(2)
    previous.button("← Previous", use_container_width=True, disabled=position == 0, on_click=_navigate, args=(position - 1,))
    following.button("Next →", use_container_width=True, disabled=position == len(DEFENSE_INDEX) - 1, on_click=_navigate, args=(position + 1,))
    st.markdown(_presenter_notes_link(_presenter_note_key(active_section)), unsafe_allow_html=True)

if active_section == "04 · Simulation lab":
    # Layer 1 is a real, deterministic sample construction, not an analogy.
    # A fixed internal seed makes parameter changes directly comparable without
    # exposing an unnecessary defense-time control.
    L1_SEED = 20260808
    if "l1_next_stage" in st.session_state:
        st.session_state.l1_stage = st.session_state.pop("l1_next_stage")
    controls, visual = st.columns([.72, 5.28])
    with controls:
        st.markdown("**DATA-GENERATING REGIME**")
        l1_family = st.selectbox("Distribution family", ["normal", "lognormal", "weibull", "exgaussian"], key="l1_family")
        l1_contam = st.selectbox("Contamination structure", ["none", "upper_tail", "symmetric", "bimodal", "point_mass"], index=1, key="l1_contam")
        l1_rate = st.slider("Contamination rate", 0.0, .30, .10, .01, key="l1_rate")
        l1_scale = st.slider("Outlier scale", 1.5, 20.0, 10.0, .5, key="l1_scale")
        l1_n = st.select_slider("Population / sample size", [100, 300, 500, 1000, 1500, 2500, 5000], value=1500, key="l1_n")
    l1_key=(l1_family,l1_contam,l1_rate,l1_scale,l1_n)
    if "l1_key" not in st.session_state or st.session_state.l1_key != l1_key:
        st.session_state.l1_key=l1_key; st.session_state.l1_stage=9; st.session_state.l1_playing=False
    with controls:
        st.markdown("**CONSTRUCTION PLAYBACK**")
        play, pause, reset = st.columns(3)
        if play.button("▶", use_container_width=True, key="l1_play"):
            st.session_state.l1_playing=True
        if pause.button("❚❚", use_container_width=True, key="l1_pause"):
            st.session_state.l1_playing=False
        if reset.button("↺", use_container_width=True, key="l1_reset"):
            st.session_state.l1_stage=0; st.session_state.l1_playing=False
        l1_speed=st.select_slider("Animation pace", ["Slow", "Normal", "Fast"], value="Normal", key="l1_speed")
        stage=st.select_slider("Construction stage", options=list(range(10)), value=9, format_func=lambda item: f"Step {item + 1} / 10", key="l1_stage")
    sample=draw_sample(DemoScenario(l1_family,l1_contam,float(l1_rate),float(l1_scale),int(l1_n),L1_SEED))
    # A real contaminated sample arrives as one mixed random sequence; the
    # original baseline-then-outliers ordering was only a teaching convention.
    construction_order=np.random.default_rng(L1_SEED + 77).permutation(l1_n)
    progress=(stage + 1) / 10
    stage_names=("mixed sample begins", "early mixed draw", "mixed draw grows", "mixed draw grows", "half the sample visible", "mixed draw grows", "contamination becomes clearer", "near-complete mixed sample", "near-complete mixed sample", "full contaminated sample")
    visible_ids=construction_order[:int(round(l1_n * progress))]
    values=sample.values[visible_ids]; visible_outliers=sample.is_outlier[visible_ids]
    full_estimates=location_estimates(sample.values)
    with visual:
        summary, *metric_cards = st.columns([2.1,1,1,1,1,1])
        with summary:
            st.markdown(f'''<div class="scenario-panel"><b>{l1_family.replace('exgaussian', 'Ex-Gaussian').title()}</b> · {l1_contam.replace('_', ' ').title()}<br>ε = {l1_rate:.0%} · scale = {l1_scale:g}× · n = {l1_n:,}<br>Expected outliers: {int(round(l1_rate*l1_n)):,}</div>''', unsafe_allow_html=True)
        for card,(name,value) in zip(metric_cards,full_estimates.items()):
            card.metric(name, f"{value:.3f}")
        st.caption(f"Step {stage + 1} of 10 · {len(values):,} visible observations: {(~visible_outliers).sum():,} inliers and {visible_outliers.sum():,} generated outliers · {stage_names[stage]}")
        fig=go.Figure()
        peak=1.0
        if len(values)>8:
            density,edges=np.histogram(values,bins=48,density=True); centers=(edges[:-1]+edges[1:])/2; peak=max(float(density.max()),.01)
            fig.add_trace(go.Scatter(x=centers,y=density,mode='lines',fill='tozeroy',name='Density',line=dict(color='#79b9e6',width=2.5),fillcolor='rgba(121,185,230,.24)'))
        if (~visible_outliers).any():
            fig.add_trace(go.Scatter(x=values[~visible_outliers],y=np.full((~visible_outliers).sum(),-.055*peak),mode='markers',name='Inliers',marker=dict(size=6,color='#6398d0',opacity=.78)))
        if visible_outliers.any():
            fig.add_trace(go.Scatter(x=values[visible_outliers],y=np.full(visible_outliers.sum(),-.055*peak),mode='markers',name='Outliers',marker=dict(size=10,color='#ff5b49',symbol='x',line=dict(width=1,color='#ffb0a7'))))
        if len(values)>8:
            current=location_estimates(values)
            for name,value in current.items(): fig.add_vline(x=value,line_width=1.5,line_dash='dot',annotation_text=name,annotation_position='top')
        fig.add_vline(x=sample.true_location,line_dash='dash',line_width=2,annotation_text='Synthetic target')
        fig.add_annotation(xref='paper',yref='paper',x=.01,y=.98,xanchor='left',yanchor='top',align='left',showarrow=False,bgcolor='rgba(8,21,37,.82)',bordercolor='#326188',borderwidth=1,text=f"<b>Mixed generated draw</b><br>Blue = inlier · Red × = generated outlier<br>{visible_outliers.sum():,} of {len(values):,} visible observations are contamination")
        fig.update_layout(height=500,xaxis_title='Observed value',yaxis_title='Density',margin=dict(l=10,r=10,t=35,b=20),legend=dict(orientation='h',y=1.02),plot_bgcolor='#081525',paper_bgcolor='#081525',yaxis=dict(range=[-.14*peak,1.15*peak]))
        st.plotly_chart(fig,use_container_width=True)
        strip=go.Figure()
        strip.add_trace(go.Scatter(x=np.arange(len(values))[~visible_outliers],y=values[~visible_outliers],mode='markers',name='Inliers',marker=dict(size=5,color='#3576a8',opacity=.55)))
        if visible_outliers.any(): strip.add_trace(go.Scatter(x=np.arange(len(values))[visible_outliers],y=values[visible_outliers],mode='markers',name='Outliers',marker=dict(size=9,color='#ff5b49',symbol='x',opacity=.9)))
        strip.add_annotation(xref='paper',yref='paper',x=.01,y=.98,xanchor='left',yanchor='top',showarrow=False,bgcolor='rgba(8,21,37,.82)',bordercolor='#326188',borderwidth=1,text='Random observation order: contamination is interleaved with inliers.')
        strip.update_layout(title='Actual generated observation order',height=390,xaxis_title='Random draw order',yaxis_title='Observed value',margin=dict(l=10,r=10,t=40,b=20),legend=dict(orientation='h',y=1.04),plot_bgcolor='#081525',paper_bgcolor='#081525')
        st.plotly_chart(strip,use_container_width=True)
    if st.session_state.l1_playing:
        if stage < 9:
            # Nine well-spaced transitions make the real mixed draw observable
            # without the 50-update websocket flood of the original animation.
            time.sleep({"Slow":3.5,"Normal":1.8,"Fast":.8}[l1_speed])
            st.session_state.l1_next_stage=stage+1
            st.rerun()
        else:
            st.session_state.l1_playing=False

if active_section == "05 · GA search":
    if "l2_from_layer1" in st.session_state:
        scenario_from_l1=st.session_state.pop("l2_from_layer1")
        st.session_state.l2_family=scenario_from_l1["family"]
        st.session_state.l2_contam=scenario_from_l1["contamination"]
        st.session_state.l2_rate=scenario_from_l1["rate"]
        st.session_state.l2_scale=scenario_from_l1["scale"]
        st.session_state.l2_sample_n=scenario_from_l1["n"]
        st.success("Layer 1 regime loaded. This mini-GA now optimizes the same pedagogical scenario.")
    controls, visual = st.columns([.72, 5.28])
    with controls:
        st.markdown("**SEARCH CONTEXT**")
        l2_family = st.selectbox("Distribution family", ["normal", "lognormal", "weibull", "exgaussian"], key="l2_family")
        l2_contam = st.selectbox("Contamination structure", ["none", "upper_tail", "symmetric", "bimodal", "point_mass"], index=1, key="l2_contam")
        l2_rate = st.slider("Contamination rate", 0.0, .30, .10, .01, key="l2_rate")
        l2_scale = st.slider("Outlier scale", 1.5, 20.0, 10.0, .5, key="l2_scale")
        l2_sample_n = st.select_slider("Teaching sample size", [100, 300, 500, 1000, 1500, 2500, 5000], value=500, key="l2_sample_n")
        l2_mutation = st.select_slider("Mutation level", options=[.05, .10, .18, .28], value=.18, format_func=lambda value: f"{value:.0%}", key="l2_mutation")
        l2_lens = st.radio("Target metric", ["MSE", "q95(MSE)"], index=1, horizontal=True, key="l2_lens", help="A pedagogical lens that changes only the synthetic terrain's shape.")
        l2_pop = st.select_slider("GA population", [36, 48, 60, 72], value=48, key="l2_pop")
        l2_seed = 20260810
        load = st.button("Generate landscape", type="primary", use_container_width=True)
        st.markdown("**GA PLAYBACK**")
        play_side, pause_side, reset_side = st.columns(3)
        if play_side.button("▶", use_container_width=True, key="l2_play"):
            st.session_state.l2_playing = True
        if pause_side.button("❚❚", use_container_width=True, key="l2_pause"):
            st.session_state.l2_playing = False
        if reset_side.button("↺", use_container_width=True, key="l2_reset"):
            st.session_state.l2_scrubber = 0; st.session_state.l2_playing = False
        speed = st.select_slider("Animation pace", ["Slow", "Normal", "Fast"], value="Normal", key="l2_speed")
    # Apply queued animation progress before the generation widget is created.
    if "l2_next_frame" in st.session_state:
        st.session_state.l2_scrubber = st.session_state.pop("l2_next_frame")
    if "l2_next_phase" in st.session_state:
        st.session_state.l2_phase = st.session_state.pop("l2_next_phase")
    key = (l2_family, l2_contam, l2_rate, l2_scale, l2_mutation, l2_pop, l2_lens, l2_seed)
    if "l2_key" not in st.session_state or st.session_state.l2_key != key or load:
        st.session_state.l2_key = key
        st.session_state.l2_scrubber = 0
        st.session_state.l2_phase = 0
        st.session_state.l2_playing = False
    demo = build_layer2_demo(*key, "generation-steps-v1")
    run, terrain = demo["run"], demo["terrain"]
    max_generation = int(run["generations"][-1])
    frame = int(st.session_state.get("l2_scrubber", 0))
    with controls:
        frame = st.slider("Generation", 0, max_generation, key="l2_scrubber")
        phase = st.select_slider("Operation inside this generation", options=list(range(5)), value=0, format_func=lambda item: ("Evaluate", "Select", "Crossover", "Mutation", "Next generation")[item], key="l2_phase")
        st.markdown("**MAP VIEW**")
        show_population = st.toggle("Population", value=True, key="l2_show_population")
        show_path = st.toggle("Best path", value=True, key="l2_show_path")
        show_contours = st.toggle("Inheritance", value=True, key="l2_show_contours")
        show_grid = st.toggle("Grid", value=True, key="l2_show_grid")
        show_contamination = st.toggle("Eliminated", value=True, key="l2_show_contamination")
    active_rate = float(l2_rate)
    with visual:
        # The generation map is the instructional focus: keep it first and tall
        # enough to be fully visible without the former summary-card row.
        components.html(cluster_map_svg(run, frame, phase, show_inheritance=show_contours, show_eliminated=show_contamination, show_grid=show_grid, show_path=show_path), height=940, scrolling=False)
        observations, target_shift = st.columns(2)
        with observations:
            sample = draw_sample(DemoScenario(l2_family, l2_contam, active_rate, l2_scale, int(l2_sample_n), l2_seed))
            obs = go.Figure()
            inliers = sample.values[~sample.is_outlier]
            outliers = sample.values[sample.is_outlier]
            density, edges = np.histogram(inliers, bins=42, density=True)
            density = np.convolve(density, np.array([1, 2, 3, 2, 1]) / 9, mode="same")
            centers = (edges[:-1] + edges[1:]) / 2
            jitter = np.random.default_rng(l2_seed + 31 * frame)
            obs.add_trace(go.Scatter(x=centers, y=density, mode="lines", line=dict(color="#8b5cf6", width=2.5, shape="spline"), fill="tozeroy", fillcolor="rgba(139,92,246,.20)", hoverinfo="skip"))
            obs.add_trace(go.Scatter(x=inliers, y=jitter.uniform(-density.max()*.075, -density.max()*.015, len(inliers)), mode="markers", marker=dict(size=4, color="#8b5cf6", opacity=.42), hoverinfo="skip"))
            if len(outliers):
                obs.add_trace(go.Scatter(x=outliers, y=jitter.uniform(-density.max()*.20, -density.max()*.09, len(outliers)), mode="markers", marker=dict(size=7, color="#ef4444", opacity=.90), hovertemplate="Outlier<extra></extra>"))
            obs.update_layout(height=190, margin=dict(l=18,r=8,t=8,b=18), showlegend=False, xaxis=dict(showgrid=True, gridcolor="#214664", griddash="dot", zeroline=False), yaxis=dict(showgrid=True, gridcolor="#214664", griddash="dot", zeroline=False, showticklabels=False), plot_bgcolor="#081525", paper_bgcolor="#081525")
            st.plotly_chart(obs, use_container_width=True)
        with target_shift:
            components.html(contamination_shift_svg(active_rate), height=190, scrolling=False)
        score_history, survivor_history = st.columns(2)
        visible_generations = run["generations"][:frame + 1]
        all_scores = run["best_scores"]
        score_span = max(float(all_scores[0] - all_scores[-1]), 1e-9)
        visible_scores = 100 * (all_scores[0] - all_scores[:frame + 1]) / score_span
        visible_scores = np.maximum.accumulate(visible_scores)
        progress = visible_generations / max_generation
        # Count actual parent indices represented in recorded offspring events.
        lineage_counts=[]
        for gen in visible_generations:
            if gen >= max_generation:
                lineage_counts.append(0); continue
            event_set=run["events"][int(gen)+1]
            parents={event.get("parent_a_index") for event in event_set if event.get("event_type")=="offspring"}
            parents|={event.get("parent_b_index") for event in event_set if event.get("event_type")=="offspring"}
            lineage_counts.append(len(parents))
        soft_grid = dict(showgrid=True, gridcolor="#214664", griddash="dot", zeroline=False)
        with score_history:
            best_score = go.Figure(go.Scatter(x=visible_generations, y=visible_scores, mode="lines", line=dict(color="#6534e8", width=3, shape="spline"), hovertemplate="Generation %{x}<br>Score %{y:.1f}<extra></extra>"))
            best_score.update_layout(title="Best demo score by generation", height=210, margin=dict(l=24,r=10,t=35,b=22), showlegend=False, xaxis=soft_grid, yaxis=soft_grid, plot_bgcolor="#081525", paper_bgcolor="#081525")
            st.plotly_chart(best_score, use_container_width=True)
        with survivor_history:
            survivors = go.Figure(go.Bar(x=visible_generations, y=lineage_counts, marker_color="#59c977", hovertemplate="Generation %{x}<br>Parents contributing %{y}<extra></extra>"))
            survivors.update_layout(title="Selected lineages by generation", height=210, margin=dict(l=24,r=10,t=35,b=22), showlegend=False, xaxis=soft_grid, yaxis=soft_grid, plot_bgcolor="#081525", paper_bgcolor="#081525", yaxis_title="Parents")
            st.plotly_chart(survivors, use_container_width=True)
        st.caption("Low-dimensional slice of the full 26-dimensional simplex; shown for visualization only.")
    st.markdown('<div class="independent-note">This layer runs its own seeded mini-GA. It does not reuse the Layer 1 sample as evidence and never represents this animated path as a thesis trajectory.</div>', unsafe_allow_html=True)
    if st.session_state.l2_playing:
        if frame < max_generation or phase < 4:
            # A complete generation has five teaching scenes; normal playback
            # deliberately leaves time to narrate each one during a defense.
            time.sleep({"Slow": 4.5, "Normal": 2.0, "Fast": .75}[speed])
            if phase < 4:
                st.session_state.l2_next_phase = phase + 1
            else:
                st.session_state.l2_next_phase = 0
                st.session_state.l2_next_frame = frame + 1
            st.rerun()
        else:
            st.session_state.l2_playing = False
            st.success("Demo run complete. Scrub the timeline or change the regime to compare a new search landscape.")

if active_section == "06 · Experiment pipeline":
    if "story_stage" not in st.session_state:
        st.session_state.story_stage = 0
    stage_buttons = st.columns(3)
    for index, (title, _claim, _what, _why) in enumerate(PIPELINE_STAGES):
        with stage_buttons[index % 3]:
            if st.button(f"{index + 1}. {title}", key=f"story_stage_{index}", use_container_width=True, type="primary" if index == st.session_state.story_stage else "secondary"):
                st.session_state.story_stage = index
    components.html(experiment_pipeline_svg(st.session_state.story_stage), height=790, scrolling=False)
    st.caption(f"You are seeing Stage {st.session_state.story_stage + 1} of 5. Select a stage manually; this visual narrative never reruns the thesis GA.")

if active_section == "07 · Results journey":
    st.markdown('<span class="badge thesis">RESULTS JOURNEY — precomputed thesis evidence</span>', unsafe_allow_html=True)
    st.caption("Discovery finds opportunities; fixed-weight evidence decides what survives.")
    result_stages = (
        ("1–2 · Discovery + Frozen I", "OPPORTUNITY", "36 → 16 → 2", "Discovery creates opportunities; frozen confirmation narrows the claim."),
        ("3 · Expanded rediscovery", "REDISCOVERY", "10 → 26", "Reopening the basis changes what the GA can discover."),
        ("4 · Strict validation", "TRANSFER SPECIALIST", "2 Weibull specialists", "Harder pressure makes the evidence local, not universal."),
        ("5A · Real-world battery", "EXTERNAL CALIBRATION", "26 / 43 parents", "Empirical transfer is calibration, not known-θ truth validation."),
        ("5B · Dirichlet audit", "AUDIT", "23 / 34 no random pass", "Benchmark retention is often meaningful, not merely GA failure."),
    )
    if "results_stage" not in st.session_state:
        st.session_state.results_stage = 0
    buttons = st.columns(5)
    for i, (label, _claim, _metric, _line) in enumerate(result_stages):
        with buttons[i]:
            if st.button(label, key=f"results_stage_{i}", use_container_width=True, type="primary" if i == st.session_state.results_stage else "secondary"):
                st.session_state.results_stage = i
                st.session_state.results_explanation = 0
    stage = st.session_state.results_stage
    label, claim, metric, interpretation = result_stages[stage]
    colors = ("#e66d4f", "#a777e3", "#54c786", "#58aee8", "#4fc3ff")
    hero, rail = st.columns([3.1, 1.05])
    with hero:
        fig = go.Figure()
        if stage == 0:
            fig.add_trace(go.Funnel(y=["Discovery regimes", "Discovery wins", "Locked confirmations"], x=[36,16,2], marker=dict(color=[colors[0],"#f3c743","#54c786"])))
            fig.update_layout(title="Opportunity → fixed-weight confirmation", height=390)
        elif stage == 1:
            fig.add_trace(go.Bar(x=["Cycle I", "Cycle II"], y=[10,26], marker_color=["#7187a4",colors[1]], text=["10 components", "26 components"], textposition="outside"))
            fig.add_annotation(x="Cycle II", y=26, text="HPF: 60% → 90%<br>CV-019 / CV-010 warm starts", showarrow=False, yshift=55)
            fig.update_layout(title="Expanded component library", height=390, yaxis_title="Learnable components")
        elif stage == 2:
            evidence = load_evidence_taxonomy()
            grades = evidence.evidence_grade.value_counts() if not evidence.empty else {}
            fig.add_trace(go.Bar(x=list(grades.index), y=list(grades.values), marker_color=colors[2]))
            fig.update_layout(title="Fixed-weight evidence taxonomy", height=390, xaxis_title="Evidence class", yaxis_title="Candidates")
        elif stage == 3:
            fig.add_trace(go.Bar(x=["Eligible parent datasets", "Parents with ≥1 corrected win"], y=[43,26], marker_color=["#7187a4",colors[3]], text=["43", "26"], textposition="outside"))
            fig.add_annotation(x="Parents with ≥1 corrected win", y=26, text="255 profile-matched FDR 5% confirmations", showarrow=False, yshift=55)
            fig.update_layout(title="Real-world external battery", height=390, yaxis_title="Parent datasets")
        else:
            audit = load_dirichlet_summary()
            total = len(audit) if not audit.empty else 34
            signals = int(audit["dirichlet_signal"].astype(str).str.lower().eq("true").sum()) if not audit.empty else 11
            fig.add_trace(go.Bar(x=["No random pass", "Some random signal", "Strongest controls pass"], y=[23, signals, 8], marker_color=["#7187a4",colors[4],"#54c786"], text=["23 / 34", f"{signals} / {total}", "8 / 8"], textposition="outside"))
            fig.update_layout(title="Dirichlet random-simplex abstain audit", height=390, yaxis_title="Regimes / controls")
        fig.update_layout(plot_bgcolor="#081525", paper_bgcolor="#081525", font_color="#e9f4ff", margin=dict(l=25,r=25,t=52,b=40), showlegend=False)
        st.plotly_chart(fig, use_container_width=True)
    with rail:
        st.markdown(f'''<div class="story-panel"><div class="story-kicker">CLAIM STATUS</div><div class="story-title" style="font-size:21px;color:{colors[stage]}">{claim}</div><div class="story-label">KEY EVIDENCE</div><div class="story-body">{metric}</div><div class="story-label" style="margin-top:18px">INTERPRETATION</div><div class="story-body">{interpretation}</div></div>''', unsafe_allow_html=True)
    if "results_explanation" not in st.session_state:
        st.session_state.results_explanation = 0
    explain_steps = ("Signal — what first appeared in this stage.", "Pressure — what stronger comparison or validation tested.", "Interpretation — the precise, bounded claim allowed by the evidence.")
    left, right = st.columns([1,4])
    with left:
        if st.button("Advance explanation", key="advance_results"):
            st.session_state.results_explanation = min(2, st.session_state.results_explanation + 1)
    with right:
        st.info(explain_steps[st.session_state.results_explanation])
    show_detail = st.toggle("Show technical detail", value=False, key="results_technical_detail")
    if show_detail:
        st.caption("Technical backup: precomputed candidate-level tables remain available below; no result is recomputed here.")
        winners = load_winners()
        if not winners.empty:
            top = winners.copy()
            top["gain"] = top["ga_rel_improvement_q95"].astype(float)
            st.dataframe(top[["distribution", "specialist_regime_id", "gate_pass", "final_selected_type", "gain"]].head(12), use_container_width=True, hide_index=True)

if active_section == "08 · Technical drill-down":
    st.markdown('<span class="badge thesis">THESIS RESULTS — precomputed research output</span>', unsafe_allow_html=True)
    winners=load_winners()
    if winners.empty: st.error('Not exported'); st.stop()
    family=st.selectbox('Distribution',sorted(winners.distribution.dropna().unique()),key='l3fam')
    subset=winners[winners.distribution==family]
    regime=st.selectbox('Regime',list(subset.specialist_regime_id.dropna().unique()))
    row=subset[subset.specialist_regime_id==regime].iloc[0]
    st.subheader(f"{family} — {regime}");st.caption(str(row.get('condition_summary',row.get('regime_key',''))))
    c1,c2,c3=st.columns(3);c1.metric('Discovery gate pass',str(row.get('gate_pass')));c2.metric('Final selected type',str(row.get('final_selected_type')));c3.metric('Best q95 benchmark',str(row.get('best_benchmark_q95_estimator')))
    weights=sorted([(name,float(row.get(f'w_{name}',0) or 0)) for name in ESTIMATOR_NAMES],key=lambda x:x[1],reverse=True)
    wf=go.Figure(go.Bar(x=[x[1] for x in weights],y=[x[0] for x in weights],orientation='h',marker_color='#e6533f'));wf.update_layout(title='26-component final weight vector',height=680,yaxis=dict(autorange='reversed'),xaxis_title='Weight')
    st.plotly_chart(wf,use_container_width=True)
    st.info(f"Relative gain in q95(MSE): {row.get('ga_rel_improvement_q95','Not exported')} · Relative gain in mean MSE: {row.get('ga_rel_improvement_mean','Not exported')}. Discovery does not equal fixed-weight confirmation.")

if active_section == "08 · Technical drill-down":
    st.markdown('<span class="badge thesis">THESIS RESULTS — precomputed research output</span>', unsafe_allow_html=True)
    st.caption('Discovery → locked / fixed weights → bootstrap CI → evidence taxonomy')
    decisions,ci,evidence,validated=load_final_decisions(),load_bootstrap_ci(),load_evidence_taxonomy(),load_validated_specialists()
    ids=list(decisions.validation_id.dropna().unique()) if not decisions.empty else []
    if not ids: st.error('Not exported'); st.stop()
    vid=st.selectbox('Candidate',ids)
    dr=decisions[decisions.validation_id==vid].iloc[0];er=evidence[evidence.validation_id==vid]
    a,b=st.columns(2)
    with a: st.subheader('Fixed-weight decision');st.write(dr.get('final_fixed_weight_validation_decision','Not exported'));st.write('Original-regime gate:',dr.get('expanded_gate_pass_mean.original_regime','Not exported'));st.write('Locked-unseen gate:',dr.get('expanded_gate_pass_mean.locked_unseen_similar','Not exported'))
    with b: st.subheader('Evidence taxonomy');st.write(er.iloc[0].get('evidence_grade','Not exported') if not er.empty else 'Not exported');st.caption(er.iloc[0].get('interpretive_note','Not exported') if not er.empty else 'Not exported')
    sub=ci[ci.validation_id==vid];fig=go.Figure()
    for mode,color in [('original_regime','#e6533f'),('locked_unseen_similar','#3576a8')]:
        x=sub[sub.validation_mode==mode]
        fig.add_trace(go.Scatter(x=x.mean_gain,y=x.validation_seed,error_x=dict(type='data',symmetric=False,array=x.mean_gain_ci_high-x.mean_gain,arrayminus=x.mean_gain-x.mean_gain_ci_low),mode='markers',name=mode,marker=dict(color=color)))
    fig.add_vline(x=0,line_dash='dash');fig.update_layout(title='Mean gain with bootstrap CI',height=400,xaxis_title='Mean gain',yaxis_title='Validation seed')
    st.plotly_chart(fig,use_container_width=True);st.caption(f'Validated specialists in curated taxonomy: {len(validated)}')

if active_section == "08 · Technical drill-down":
    st.markdown('<span class="badge thesis">THESIS RESULTS — external evidence</span>', unsafe_allow_html=True)
    st.caption("These two audits answer different questions and neither retrains a discovered estimator.")
    real, audit = st.columns(2)
    with real:
        st.markdown('''<div class="story-panel"><div class="story-kicker">REAL-WORLD EXTERNAL BATTERY</div><div class="story-title">Empirical calibration</div><div class="story-label">WHAT IT TESTS</div><div class="story-body">Frozen specialists are applied to public datasets without retraining. Repeated subsamples are assessed against the empirical full-sample mean.</div><div class="story-label" style="margin-top:20px">THESIS RESULT</div><div class="story-body">At least one corrected win occurred in 26 of 43 eligible parent datasets; 255 profile-matched comparisons survived false-discovery-rate control.</div><div class="story-label" style="margin-top:20px">QUESTION</div><div class="story-body">Does the supported signal transfer to empirical data?</div></div>''', unsafe_allow_html=True)
    with audit:
        st.markdown('''<div class="story-panel"><div class="story-kicker">RANDOM DIRICHLET ABSTAIN AUDIT</div><div class="story-title">Simplex sanity check</div><div class="story-label">WHAT IT TESTS</div><div class="story-body">Random Dirichlet composites are evaluated in benchmark-retained regimes under the original dual gate. This audit does not rerun the GA.</div><div class="story-label" style="margin-top:20px">QUESTION</div><div class="story-body">Could arbitrary weight vectors reveal composite signal where the selected GA candidate was retained by the benchmark?</div></div>''', unsafe_allow_html=True)
    dirichlet_summary, dirichlet_signals = load_dirichlet_summary(), load_dirichlet_signals()
    if not dirichlet_summary.empty:
        signal_count=int(dirichlet_summary["dirichlet_signal"].astype(str).str.lower().eq("true").sum())
        total=len(dirichlet_summary)
        metric_a, metric_b, metric_c = st.columns(3)
        metric_a.metric("Audited regimes", total)
        metric_b.metric("Regimes with Dirichlet signal", signal_count)
        metric_c.metric("Audit rule", "4,000 draws · 8 seeds")
        plot_data=dirichlet_summary.sort_values("total_seed_stable_passes", ascending=False).head(12)
        audit_fig=go.Figure(go.Bar(x=plot_data["validation_id"], y=plot_data["total_seed_stable_passes"], marker_color=["#f3c743" if str(v).lower()=="true" else "#526a85" for v in plot_data["dirichlet_signal"]], hovertemplate="%{x}<br>Seed-stable passes: %{y}<extra></extra>"))
        audit_fig.update_layout(title="Dirichlet audit: seed-stable random-search passes by regime", height=350, yaxis_title="Passes across audit seeds", plot_bgcolor="#081525", paper_bgcolor="#081525")
        st.plotly_chart(audit_fig, use_container_width=True)
        st.caption("Gold bars indicate a reported Dirichlet signal. A signal calls for the abstention to be revisited; it is not a replacement for fixed-weight confirmation.")
    else:
        st.info("Dirichlet audit results were not exported to this dashboard bundle.")

if active_section == "00 · Cover":
    logo, opening = st.columns([1, 3.4])
    with logo:
        st.image("assets/university_of_hull_logo.jpeg", use_container_width=True)
    with opening:
        st.markdown("## Building Better Estimators")
        st.markdown("### Benchmark-gated, regime-conditional composite mean estimation via genetic search")
        st.caption("MSc Artificial Intelligence · Thesis Defense · Alvaro Rivera-Eraso · Supervisor · University of Hull")
        st.markdown("<br>", unsafe_allow_html=True)
        start, results, appendix = st.columns([1.45, 1, 1])
        start.button("Start Defense →", type="primary", use_container_width=True, on_click=_navigate, args=(1,))
        results.button("Jump to Results", use_container_width=True, on_click=_navigate, args=(7,))
        appendix.button("Technical Appendix", use_container_width=True, on_click=_navigate, args=(8,))
    st.info("Conditional estimator discovery — not universal GA superiority.")

if active_section == "01 · Research logic":
    st.markdown("""<style>
    .research-logic-nav .stButton>button{min-height:3.6rem!important;padding:.65rem .75rem!important;font-size:1.03rem!important;line-height:1.18!important;white-space:normal!important}
    .research-logic-nav .stButton>button[kind="primary"]{box-shadow:0 0 18px rgba(93,62,221,.38)!important}
    .research-logic-next .stButton>button{min-height:3.25rem!important;padding:.65rem 1.25rem!important;font-size:1.05rem!important}
    </style>""", unsafe_allow_html=True)
    st.markdown("<div class='layer-heading'>Research logic: why the experiment exists</div>", unsafe_allow_html=True)
    if "research_panel" not in st.session_state:
        st.session_state.research_panel = 0
    st.markdown('<div class="research-logic-nav">', unsafe_allow_html=True)
    panel_buttons = st.columns(5, gap="medium")
    for i, (label, _what, _why, _say) in enumerate(RESEARCH_PANELS):
        with panel_buttons[i]:
            st.button(label, key=f"research_panel_{i}", use_container_width=True, type="primary" if i == st.session_state.research_panel else "secondary", on_click=_set_presenter_state, args=("research_panel", i))
    st.markdown('</div>', unsafe_allow_html=True)
    # Match the full defense-canvas scale used by Layer 5, leaving room for the
    # primary story plus the technical notation support band below it.
    components.html(research_logic_svg(st.session_state.research_panel), height=1000, scrolling=False)
    st.markdown('<div class="research-logic-next">', unsafe_allow_html=True)
    st.button("Continue to simulated world →", type="primary", on_click=_navigate, args=(2,))
    st.markdown('</div>', unsafe_allow_html=True)

if active_section == "03 · Monte Carlo engine":
    st.markdown("""<style>
    .monte-carlo-tabs .stButton>button{min-height:3.5rem!important;padding:.65rem 1rem!important;font-size:1.04rem!important;white-space:normal!important}
    .validation-stage-tabs .stButton>button{min-height:3.8rem!important;padding:.55rem .7rem!important;font-size:.96rem!important;line-height:1.2!important;white-space:normal!important}
    </style>""", unsafe_allow_html=True)
    if "monte_carlo_view" not in st.session_state:
        st.session_state.monte_carlo_view = "engine"
    st.markdown('<div class="monte-carlo-tabs">', unsafe_allow_html=True)
    engine_tab, validation_tab = st.columns(2)
    with engine_tab:
        st.button("Monte Carlo measurement engine", key="monte_carlo_engine", use_container_width=True, type="primary" if st.session_state.monte_carlo_view == "engine" else "secondary", on_click=_set_presenter_state, args=("monte_carlo_view", "engine"))
    with validation_tab:
        st.button("Data-generating world validation", key="monte_carlo_validation", use_container_width=True, type="primary" if st.session_state.monte_carlo_view == "validation" else "secondary", on_click=_set_presenter_state, args=("monte_carlo_view", "validation"))
    st.markdown('</div>', unsafe_allow_html=True)
    if st.session_state.monte_carlo_view == "engine":
        components.html(defense_scene_svg(5), height=910, scrolling=False)
    else:
        if "validation_stage" not in st.session_state:
            st.session_state.validation_stage = 0
        st.markdown('<div class="validation-stage-tabs">', unsafe_allow_html=True)
        validation_buttons = st.columns(4, gap="medium")
        for index, (title, *_detail) in enumerate(VALIDATION_STAGES):
            with validation_buttons[index]:
                st.button(title, key=f"validation_stage_{index}", use_container_width=True, type="primary" if index == st.session_state.validation_stage else "secondary", on_click=_set_presenter_state, args=("validation_stage", index))
        st.markdown('</div>', unsafe_allow_html=True)
        components.html(validation_scene_svg(st.session_state.validation_stage), height=860, scrolling=False)

DEFENSE_SCENE_SECTION = {
    "02 · Data-generating world": 4,
    "09 · Conclusions": 6,
}
if active_section in DEFENSE_SCENE_SECTION:
    scene_height = 860 if active_section == "02 · Data-generating world" else 770
    components.html(defense_scene_svg(DEFENSE_SCENE_SECTION[active_section]), height=scene_height, scrolling=False)
    if active_section == "09 · Conclusions":
        closing_a, closing_b = st.columns(2)
        closing_a.button("Go to technical appendix", use_container_width=True, on_click=_navigate, args=(8,))
        closing_b.button("Back to results", type="primary", use_container_width=True, on_click=_navigate, args=(7,))
    else:
        st.caption("This methodological scene prepares the live simulations; it does not present a result.")
