"""Structured formula guides for the hidden presenter-note window.

Each entry mirrors formulas already visible in the Research Logic panels.  The
presenter view expands each formula into short symbol-by-symbol speaking cues;
it does not introduce new thesis claims or alter the audience-facing slides.
"""

FORMULA_GUIDES = {
    "research_problem": [
        (
            "1 · Data-generating regime",
            "ℛ = (F₀, γ, c, m, n)",
            [
                ("ℛ", "The complete data-generating regime used to define one experimental condition."),
                ("F₀", "The baseline distribution family before contamination is introduced."),
                ("γ", "The contamination rate: the proportion of observations generated by the contamination mechanism."),
                ("c", "The contamination scale or severity: how far the contaminating observations are displaced."),
                ("m", "The contamination mechanism, such as upper-tail, symmetric, point-mass, or another defined mechanism."),
                ("n", "The sample size used in that regime."),
            ],
        ),
        (
            "2 · Distribution induced by the regime",
            "F_ℛ = (1−γ)F₀ + γG₍m,c₎(F₀)",
            [
                ("F_ℛ", "The actual sampling distribution produced by regime ℛ."),
                ("(1−γ)F₀", "The uncontaminated part of the distribution; it carries proportion 1−γ of the probability mass."),
                ("γG₍m,c₎(F₀)", "The contaminating component; it carries proportion γ of the probability mass."),
                ("G₍m,c₎", "The contamination operator: m determines the mechanism and c determines its severity."),
                ("Interpretation", "Changing ℛ changes F_ℛ, so the finite-sample risk ranking of estimators can also change."),
            ],
        ),
        (
            "3 · Fixed estimand",
            "θ(F) = μ_F = E_F[X]",
            [
                ("θ(F)", "The target functional evaluated at distribution F."),
                ("μ_F", "Notation for the population mean under F."),
                ("E_F[X]", "The expected value of X when X follows F."),
                ("Key point", "The estimand remains the population mean. The regime changes the sampling environment, not what is being estimated."),
            ],
        ),
    ],
    "research_objective": [
        (
            "1 · Fixed target",
            "θ(F) = μ_F = E_F[X]",
            [
                ("θ(F)", "The statistical target of the study."),
                ("μ_F", "The population mean under distribution F."),
                ("E_F[X]", "The expectation of X under F."),
                ("Key point", "Every candidate and every benchmark estimates the same target."),
            ],
        ),
        (
            "2 · GA composite candidate",
            "θ̂₍w,n₎ = Σⱼ₌₁ᴸ wⱼTⱼ,n",
            [
                ("θ̂₍w,n₎", "The composite estimator produced by one GA weight vector at sample size n."),
                ("Tⱼ,n", "The j-th named base estimator evaluated at sample size n."),
                ("wⱼ", "The weight assigned by the candidate solution to estimator j."),
                ("L", "The number of learnable estimators in the component bank."),
                ("Σ", "All weighted component estimates are added to form one composite estimate."),
            ],
        ),
        (
            "3 · Search space",
            "w ∈ Δ_L = {w ∈ [0,1]ᴸ : Σⱼ wⱼ = 1}",
            [
                ("w", "The complete vector of GA weights."),
                ("Δ_L", "The L-dimensional probability simplex."),
                ("wⱼ ≥ 0", "No estimator receives a negative contribution."),
                ("Σⱼwⱼ = 1", "All weights sum to 100%, so the candidate remains a convex mixture."),
                ("Interpretation", "The GA searches estimator recipes, not arbitrary black-box formulas."),
            ],
        ),
    ],
    "research_hypotheses": [
        (
            "Hypothesis chain",
            "H1 → H2 → H3 → H4",
            [
                ("H1", "No single admissible estimator should be uniformly best across incompatible regimes."),
                ("H2", "Finite-sample estimator performance should depend on the regime and therefore on F_ℛ and n."),
                ("H3", "A simplex-constrained GA composite may help, but only in selected regimes."),
                ("H4", "The benchmark gate must be allowed to reject a discovered candidate and retain the benchmark."),
                ("Interpretation", "The chain moves from regime dependence to selective opportunity and finally to evidence control."),
            ],
        ),
        (
            "Fixed target behind all four hypotheses",
            "θ(F) = μ_F = E_F[X]",
            [
                ("θ(F)", "The target functional remains fixed across all hypotheses."),
                ("μ_F = E_F[X]", "All comparisons concern estimation of the population mean."),
                ("Key point", "The hypotheses concern which estimator is justified, not a changing estimand."),
            ],
        ),
    ],
    "research_target": [
        (
            "1 · Target",
            "θ(F) = μ_F = E_F[X]",
            [
                ("θ(F)", "The estimand or population quantity the procedure is trying to estimate."),
                ("μ_F", "The population mean under F."),
                ("E_F[X]", "The expectation of X under F."),
                ("Condition", "The target is defined whenever the relevant first moment exists."),
            ],
        ),
        (
            "2 · Composite estimator",
            "θ̂₍w,n₎ = Σⱼ₌₁ᴸ wⱼTⱼ,n",
            [
                ("θ̂₍w,n₎", "The final estimate produced by one candidate recipe."),
                ("Tⱼ,n", "A named, inspectable component estimator."),
                ("wⱼ", "The proportion assigned to that component."),
                ("L", "The total number of available learnable components."),
            ],
        ),
        (
            "3 · Simplex constraint",
            "w ∈ Δ_L = {w ∈ [0,1]ᴸ : Σⱼ₌₁ᴸ wⱼ = 1}",
            [
                ("w ∈ Δ_L", "Every candidate weight vector must lie on the simplex."),
                ("wⱼ ≥ 0", "Weights cannot be negative."),
                ("Σⱼwⱼ = 1", "Weights sum to one, so they can be read directly as proportions."),
                ("Interpretation", "Simplex validity makes the recipe interpretable; it does not by itself prove lower risk or robustness."),
            ],
        ),
    ],
    "research_why_win": [
        (
            "1 · Finite-sample MSE decomposition",
            "MSE₍F,n₎(θ̂₍w,n₎) = Bₙ(w,F)² + Vₙ(w,F)",
            [
                ("MSE₍F,n₎", "Mean squared error under distribution F at sample size n."),
                ("Bₙ(w,F)", "Finite-sample bias of the composite relative to μ_F."),
                ("Bₙ(w,F)²", "The squared bias contribution to MSE."),
                ("Vₙ(w,F)", "The finite-sample variance of the composite estimator."),
                ("Interpretation", "A composite can accept some bias only if it obtains enough variance reduction to lower total MSE."),
            ],
        ),
        (
            "2 · Composite bias",
            "Bₙ(w,F) = Σⱼ₌₁ᴸ wⱼ{E_F[Tⱼ,n] − μ_F}",
            [
                ("E_F[Tⱼ,n]", "The expected value of component estimator j under F."),
                ("E_F[Tⱼ,n] − μ_F", "The finite-sample bias of component j for the population mean."),
                ("wⱼ", "The weight determining how much that component contributes to composite bias."),
                ("Σ", "The composite bias is the weighted combination of the component biases."),
            ],
        ),
        (
            "3 · Variance",
            "Vₙ(w,F) = Var_F(θ̂₍w,n₎)",
            [
                ("Vₙ(w,F)", "The sampling variability of the fixed-weight composite."),
                ("Var_F", "Variance taken under repeated samples from F."),
                ("θ̂₍w,n₎", "The same composite estimator whose bias was defined above."),
            ],
        ),
        (
            "4 · Condition for beating the sample mean",
            "Bₙ(w,F)² + Vₙ(w,F) < Var_F(X̄ₙ)",
            [
                ("Left-hand side", "The total MSE of the composite: squared bias plus variance."),
                ("Var_F(X̄ₙ)", "The MSE of the sample mean when the sample mean is unbiased for μ_F."),
                ("<", "The composite wins only when its total finite-sample error is smaller."),
                ("Key interpretation", "Variance reduction must be large enough to pay for any squared bias introduced by the mixture."),
            ],
        ),
    ],
}
