"""Simple presenter notes for the five didactic Layer 1 views."""

RESEARCH_PRESENTER_NOTES = {
    "research_problem": (
        "Layer 1 · Why a problem?",
        "Research framing",
        [
            "Start with the simplest idea: the target stays fixed, but the statistical environment can change.",
            "The target is always the population mean: theta of F equals mu F equals E of X.",
            "In clean, near-symmetric data, the sample mean can be very efficient, so replacement should be difficult.",
            "With skewness, tails or contamination, extreme observations can change finite-sample risk and the estimator ranking can change.",
            "The logic is: change the regime, change risk, and the best admissible estimator may also change.",
            "Do not say the mean is bad. Say its relative performance can change across regimes.",
            "Do not claim a universal robust winner either. The thesis starts from the opposite idea: no universal winner is assumed.",
            "Simple closing sentence: the study asks which estimator is justified inside a defined regime.",
        ],
        "Now that the problem is clear, I can state the exact question the research programme asks.",
    ),
    "research_objective": (
        "Layer 1 · What are we asking?",
        "Research objective and questions",
        [
            "Main question: can evolutionary search find an interpretable improvement that survives independent evidence?",
            "The programme has four steps: search, freeze, challenge, and accept or abstain.",
            "Search proposes simplex weight vectors. Freeze means the candidate recipe is locked.",
            "Challenge means fresh evidence, stronger comparators, new seeds or related regimes are used without retraining.",
            "Accept or abstain means the benchmark gate decides whether replacement is supported.",
            "RQ1 asks where a composite can improve. RQ2 asks whether frozen gains survive. RQ3 asks what changes with a stronger 26-component basis. RQ4 asks whether validated specialists transfer.",
            "Important: a promising candidate is not yet a result.",
            "Success can be a supported specialist or a justified decision to keep the benchmark.",
            "Simple closing sentence: search proposes; validation decides.",
        ],
        "Before looking at results, I make the expected pattern explicit with H1 to H4.",
    ),
    "research_hypotheses": (
        "Layer 1 · What should happen?",
        "H1–H4",
        [
            "These four hypotheses form one chain, not four unrelated statements.",
            "H1: no universal estimator. Different regimes can have different winners.",
            "H2: performance depends on the regime because finite-sample risk changes with the induced distribution and sample size.",
            "H3: the GA should help only selectively. I do not expect broad GA dominance.",
            "H4: the gate controls the claim. If independent evidence does not support replacement, the benchmark stays.",
            "The reasoning chain is: scope, regime dependence, selective opportunity, claim control.",
            "A final pattern with only a few narrow winners and many retained benchmarks is compatible with these hypotheses.",
            "Benchmark retention is therefore not a failed GA result. It is an intended scientific outcome.",
            "Simple closing sentence: the expected result is selective improvement, not universal superiority.",
        ],
        "Next I separate the scientific target from the object the GA is actually allowed to change.",
    ),
    "research_target": (
        "Layer 1 · What can the GA change?",
        "Fixed target and simplex",
        [
            "The GA never changes the scientific target. The target remains theta(F) = mu_F = E_F[X].",
            "What evolves is only the estimator recipe: a vector of weights over named base estimators.",
            "The composite estimator is the weighted sum of those named estimators.",
            "The simplex rule is easy: every weight is non-negative and all weights add to one, or 100 percent.",
            "This keeps the final recipe inspectable and interpretable.",
            "The example bars on screen are only a visual example of a valid mixture, not a thesis result.",
            "A simplex-valid vector is not automatically robust, admissible on every support, or better than the benchmark.",
            "Interpretability and superiority are separate questions.",
            "Simple closing sentence: the estimand never moves; only the recipe evolves.",
        ],
        "A valid recipe can still lose, so the next question is the statistical condition under which a mixture can actually improve.",
    ),
    "research_why_win": (
        "Layer 1 · When can a mixture win?",
        "Finite-sample bias–variance logic",
        [
            "The key equation is simple: MSE equals squared bias plus variance.",
            "A robust mixture may introduce some bias relative to the population mean.",
            "But it may also reduce variance or reduce sensitivity to extreme observations.",
            "The mixture improves only when the variance reduction is large enough to pay for the squared bias cost.",
            "Under clean light-tailed symmetry, the sample mean is already highly efficient, so there may be little room to improve.",
            "Under skewness, tails or contamination, finite-sample instability can create selective opportunity.",
            "The displayed dominance inequality compares the composite with the sample mean, but the thesis final gate is stricter.",
            "The final candidate must beat the strongest admissible benchmark on both mean MSE and q95 MSE.",
            "q95 protects difficult-case performance; it is not a p-value.",
            "Simple closing sentence: validity creates a candidate, the bias–variance trade-off creates opportunity, and the gate decides the claim.",
        ],
        "Simulation now lets me measure this trade-off against known truth.",
    ),
}
