"""Simple presenter notes for the five didactic Layer 1 views."""

RESEARCH_PRESENTER_NOTES = {
    "research_problem": (
        "Layer 1 · Why a problem?",
        "Research framing",
        [
            "FIXED TARGET|The target stays fixed.",
            "CONDITIONS|The data conditions change.",
            "PERFORMANCE|Estimator performance changes with those conditions.",
            "CONCLUSION|The best estimator can be regime-dependent.",
        ],
        "This leads to the research question.",
    ),
    "research_objective": (
        "Layer 1 · What are we asking?",
        "Research objective and questions",
        [
            "MAIN QUESTION|Can the GA find an improvement that survives validation?",
            "DISCOVER · RQ1|Where can a composite improve?",
            "CONFIRM · RQ2|Do the gains survive with frozen weights?",
            "EXPAND · RQ3|Move from 10 to 26 estimators.",
            "TRANSFER · RQ4|Does the validated specialist transfer?",
            "PROCESS|Search → Freeze → Challenge → Accept / Abstain.",
            "KEY IDEA|Search proposes. Validation decides.",
        ],
        "Next, I show what we expect to happen.",
    ),
    "research_hypotheses": (
        "Layer 1 · What should happen?",
        "H1–H4",
        [
            "These four hypotheses form one chain, not four unrelated statements.",
            "H1: no universal estimator. Different regimes can have different winners.",
            "H2: performance depends on the regime because finite-sample risk changes with the induced distribution and sample size.",
            "H3: the GA should help only selectively. I do not expect broad GA dominance.",
            "H4: the gate controls the claim. If independent evidence does not support replacement, the benchmark stays.",
            "The reasoning chain is: scope, regime dependence, selective opportunity, claim control.",
            "A final pattern with only a few narrow winners and many retained benchmarks is compatible with these hypotheses.",
            "Benchmark retention is therefore not a failed GA result. It is an intended scientific outcome.",
            "Simple closing sentence: the expected result is selective improvement, not universal superiority.",
        ],
        "Next I separate the scientific target from the object the GA is actually allowed to change.",
    ),
    "research_target": (
        "Layer 1 · What can the GA change?",
        "Fixed target and simplex",
        [
            "The GA never changes the scientific target. The target remains theta(F) = mu_F = E_F[X].",
            "What evolves is only the estimator recipe: a vector of weights over named base estimators.",
            "The composite estimator is the weighted sum of those named estimators.",
            "The simplex rule is easy: every weight is non-negative and all weights add to one, or 100 percent.",
            "This keeps the final recipe inspectable and interpretable.",
            "The example bars on screen are only a visual example of a valid mixture, not a thesis result.",
            "A simplex-valid vector is not automatically robust, admissible on every support, or better than the benchmark.",
            "Interpretability and superiority are separate questions.",
            "Simple closing sentence: the estimand never moves; only the recipe evolves.",
        ],
        "A valid recipe can still lose, so the next question is the statistical condition under which a mixture can actually improve.",
    ),
    "research_why_win": (
        "Layer 1 · When can a mixture win?",
        "Finite-sample bias–variance logic",
        [
            "The key equation is simple: MSE equals squared bias plus variance.",
            "A robust mixture may introduce some bias relative to the population mean.",
            "But it may also reduce variance or reduce sensitivity to extreme observations.",
            "The mixture improves only when the variance reduction is large enough to pay for the squared bias cost.",
            "Under clean light-tailed symmetry, the sample mean is already highly efficient, so there may be little room to improve.",
            "Under skewness, tails or contamination, finite-sample instability can create selective opportunity.",
            "The displayed dominance inequality compares the composite with the sample mean, but the thesis final gate is stricter.",
            "The final candidate must beat the strongest admissible benchmark on both mean MSE and q95 MSE.",
            "q95 protects difficult-case performance; it is not a p-value.",
            "Simple closing sentence: validity creates a candidate, the bias–variance trade-off creates opportunity, and the gate decides the claim.",
        ],
        "Simulation now lets me measure this trade-off against known truth.",
    ),
}
