"""Accessible presenter cues for Layer 9 · Technical drill-down."""

TECHNICAL_PRESENTER_NOTES = {
    "appendix_A": (
        "Appendix A · GA mechanics",
        "Technical backup",
        [
            "INDIVIDUAL|w = one estimator recipe.",
            "C MATRIX|Fixed Monte Carlo outputs from the base estimators.",
            "EVALUATE|Every new w → Cw → loss → fitness.",
            "EVOLVE|Selection → crossover → mutation → new w → evaluate again.",
            "SIMPLEX|Weights are non-negative and sum to 1.",
            "WARM START|A previous winner may enter again, but gets no bonus.",
            "CLAIM|Fitness searches. Frozen validation decides.",
        ],
        "Open Metrics & Gate only if the committee asks how acceptance is decided.",
    ),
    "appendix_B": (
        "Appendix B · Metrics & gate",
        "Technical backup",
        [
            "TARGET|θ(F) = E[X].",
            "MSE|Average squared error.",
            "q95|Upper-tail squared error — difficult cases.",
            "GAIN|Positive gain = candidate has lower risk.",
            "GATE|ΔMSE ≥ 0 AND Δq95 ≥ 0.",
            "CI|If the interval crosses zero, replacement is uncertain.",
            "BENCHMARK|Compare against the strongest admissible benchmark.",
        ],
        "Open Technical Results only if exact candidates or numbers are requested.",
    ),
    "appendix_C": (
        "Appendix C · Technical results",
        "Technical backup",
        [
            "FIRST FUNNEL|36 → 16 → 2 confirmed.",
            "EXPANDED|26 learnable → 12 discovery winners.",
            "TAXONOMY|25 → 2 transfer · 10 local · 7 near-gate · 6 controls.",
            "SPECIALISTS|FWVR011 / FWVR012 pass locked-unseen but fail original mode.",
            "REAL DATA|26/43 eligible parents show corrected specialist wins.",
            "DEPTH|255 subgroup wins remain after correcting for many tests.",
            "AUDIT|23/34 no random pass · 8/8 strongest controls pass.",
            "CLAIM|Narrow specialists — not universal winners.",
        ],
        "Answer the exact question and stop; do not replay the full Results section.",
    ),
    "appendix_D": (
        "Appendix D · Committee Q&A",
        "Technical backup",
        [
            "WHY GA?|Search many interpretable recipes across generations.",
            "WHY AI?|Evolution can generate and improve estimator mixtures, not only select one fixed estimator.",
            "WHY q95?|Average risk can hide difficult cases.",
            "WHY FREEZE?|Prevent adaptation to confirmation data.",
            "WHY RETAIN?|The framework is allowed to say: benchmark wins.",
            "REAL DATA?|Transfer evidence — not known population truth.",
            "NOVELTY?|Integrated AI search + interpretable estimator design + frozen claim control.",
            "LIMIT?|Known truth is simulation-based; strongest gains are narrow.",
            "MAIN CONTRIBUTION|A reusable AI search framework with evidence-controlled acceptance.",
        ],
        "Give the short answer first. Add detail only if the committee asks.",
    ),    "appendix_E": (
        "Appendix E · Hard numbers",
        "Technical backup",
        [
            "CORE|N=100 · G=20/fold · K=3 · seeds 101/202.",
            "INIT|Dirichlet α = 0.5 or 1.0.",
            "TOURNAMENT|2 or 3 candidates compete; the better one becomes a parent.",
            "MUTATION|μ₀ = 0.12 or 0.18 → floor 0.05 · log decay.",
            "DIVERSITY|Elites 1/2 · immigration 5–10% every 15 generations.",
            "STOP|Check every 5 generations · patience 3 · δ = 0.005.",
            "FITNESS|70% q95 + 30% maximum loss + regularisation.",
            "DISCOVERY I|10 components · HPF 60% → 80%.",
            "FROZEN I|8 new seeds · R=500 · B=500 · no retraining.",
            "DISCOVERY II|26 components · HPF 60% → 90% · CV-019/CV-010 warm starts.",
            "FROZEN II|Weights fixed again · original + locked-unseen validation.",
            "AUDIT|4,000 random weights × 8 seeds · α=0.30 · R=500.",
        ],
        "Open Estimator Bases if the committee asks exactly which estimators formed each search space.",
    ),
    "appendix_F": (
        "Appendix F · Estimator bases",
        "Technical backup",
        [
            "DISCOVERY I · 10|Mean · Median · Trim20 · Harmonic · Geometric · HSM · Parzen · Trimean · Huber · Biweight.",
            "DISCOVERY II · 26|Keep the original 10 and add 16 modern robust components.",
            "WINSORISED · +3|5% · 10% · 20%.",
            "MOM · +3|k = 5 · 10 · 20 blocks.",
            "CATONI-TYPE · +5|a = 0.05 · 0.10 · 0.20 · 0.35 · 0.50.",
            "TUNED HUBER · +5|k = 0.75 · 1.00 · 1.345 · 1.75 · 2.00.",
            "SUPPORT|Harmonic and geometric means require positive data.",
            "MEANING|Stage 3 expanded what the GA could build, not only what it competed against.",
        ],
        "Return to the committee question; this tab is only the exact estimator lookup.",
    ),

}
