"""Accessible presenter cues for Layer 8 · Technical drill-down."""

TECHNICAL_PRESENTER_NOTES = {
    "appendix_A": (
        "Appendix A · GA mechanics",
        "Technical backup",
        [
            "INDIVIDUAL|w = one estimator recipe.",
            "C MATRIX|Fixed Monte Carlo outputs from the base estimators.",
            "EVALUATE|Every new w → Cw → loss → fitness.",
            "EVOLVE|Selection → crossover → mutation → new w → evaluate again.",
            "SIMPLEX|Weights are non-negative and sum to 1.",
            "WARM START|A previous winner may enter again, but gets no bonus.",
            "CLAIM|Fitness searches. Frozen validation decides.",
        ],
        "Open Metrics & Gate only if the committee asks how acceptance is decided.",
    ),
    "appendix_B": (
        "Appendix B · Metrics & gate",
        "Technical backup",
        [
            "TARGET|θ(F) = E[X].",
            "MSE|Average squared error.",
            "q95|Upper-tail squared error — difficult cases.",
            "GAIN|Positive gain = candidate has lower risk.",
            "GATE|ΔMSE ≥ 0 AND Δq95 ≥ 0.",
            "CI|If the interval crosses zero, replacement is uncertain.",
            "BENCHMARK|Compare against the strongest admissible benchmark.",
        ],
        "Open Technical Results only if exact candidates or numbers are requested.",
    ),
    "appendix_C": (
        "Appendix C · Technical results",
        "Technical backup",
        [
            "FIRST FUNNEL|36 → 16 → 2 confirmed.",
            "EXPANDED|26 learnable → 12 discovery winners.",
            "TAXONOMY|25 → 2 transfer · 10 local · 7 near-gate · 6 controls.",
            "SPECIALISTS|FWVR011 / FWVR012 pass locked-unseen but fail original mode.",
            "REAL DATA|26/43 eligible parents show corrected specialist wins.",
            "DEPTH|255 subgroup wins remain after correcting for many tests.",
            "AUDIT|23/34 no random pass · 8/8 strongest controls pass.",
            "CLAIM|Narrow specialists — not universal winners.",
        ],
        "Answer the exact question and stop; do not replay the full Results section.",
    ),
    "appendix_D": (
        "Appendix D · Committee Q&A",
        "Presenter-only help · not rendered in the audience-facing Technical drill-down",
        [
            "Why use a genetic algorithm?|Because I am searching many interpretable weight combinations across generations. The GA proposes candidates on the simplex. It does not decide the final scientific claim.",
            "Why not just select one robust estimator?|Because no single estimator is best across all regimes. The thesis tests whether a convex mixture can improve the bias–variance trade-off in selected regimes.",
            "Why q95?|Because average performance can hide difficult cases. q95 is the 95th percentile of replicate squared errors. It is not a p-value.",
            "What is frozen validation?|The weights are locked before new evidence is evaluated. There is no retraining, so the candidate cannot adapt to the validation data.",
            "Why do FWVR011 and FWVR012 pass locked-unseen but fail original-regime validation?|Because they are narrow transfer specialists, not general Weibull winners. That contrast defines the boundary of the claim instead of hiding it.",
            "What do real-data results prove?|They show external empirical support, not known-truth validation. The full-sample empirical mean is a reference; the population mean remains unknown.",
            "Why is benchmark retention a result?|Because the design allows the GA to lose. If independent evidence does not support replacement, keeping the strongest admissible benchmark is the correct scientific decision.",
            "What does the 11/34 Dirichlet signal mean?|It means some retained cells deserve another look. It does not erase the 23/34 no-pass cells, and it does not replace fixed-weight confirmation.",
            "What is the strongest contribution?|A reproducible framework that knows when to claim improvement and when to keep the benchmark. The contribution combines statistical targeting, interpretable AI search and explicit claim control.",
            "What is the main limitation?|The strongest known-truth evidence is simulation-based and the confirmed gains are narrow. That is why the final claim is conditional rather than universal.",
            "What exact hyperparameters did you use?|Open Appendix E · Hard numbers. It contains the population, operators, mutation, stopping, fitness penalties, HPF budgets and stage-by-stage changes.",
            "Which estimators were learnable in each discovery cycle?|Open Appendix F · Estimator bases. Discovery I used 10 components; Discovery II kept those 10 and added 16 modern robust components.",
            "What would you do next?|I would test prospective transfer in new domains without changing the frozen specialists. I would also investigate the Dirichlet-signal cells and seek independent external replications.",
        ],
        "Answer the committee question directly, then return to the presentation. These prompts are presenter support only.",
    ),
    "appendix_E": (
        "Appendix E · Hard numbers",
        "Technical backup",
        [
            "CORE|100 candidates · 20 generations/fold · 3 folds · seeds 101/202.",
            "INIT|Dirichlet creates random valid starting weights. α=0.5 favors more uneven recipes; α=1.0 gives a neutral random spread.",
            "TOURNAMENT|Pick 2 or 3 candidates at random → compare fitness → the best becomes a parent.",
            "MUTATION|Small random change to a child's weights. Initial chance = 12% or 18%; it slowly falls toward 5%.",
            "DIVERSITY|Prevent everyone becoming too similar: keep best 1–2 + replace worst 5–10% with fresh recipes every 15 generations.",
            "STOP|Check every 5 generations. After 3 weak checks with <0.5% improvement, stop early.",
            "FITNESS|70% q95 tail risk + 30% worst scenario loss + penalties for unstable, biased or dominated recipes.",
        ],
        "Open Estimator Bases if the committee asks exactly which estimators formed each search space.",
    ),
    "appendix_F": (
        "Appendix F · Estimator bases",
        "Technical backup",
        [
            "DISCOVERY I · 10|Mean · Median · Trim20 · Harmonic · Geometric · HSM · Parzen · Trimean · Huber · Biweight.",
            "DISCOVERY II · 26|Original 10 + 16 new: Winsorized 5/10/20 · MOM 5/10/20 · Catoni .05/.10/.20/.35/.50 · Huber .75/1/1.345/1.75/2.",
            "WINSORIZED · +3|Cap the lowest/highest 5%, 10% or 20%, then average. Extremes stay, but their influence is limited.",
            "MOM · +3|Split data into 5, 10 or 20 blocks → mean each block → take the median. k = number of blocks.",
            "CATONI-TYPE · +5|Robust mean that softens large deviations. a controls how strongly that softening acts; five levels were tested.",
            "TUNED HUBER · +5|Mean-like near the centre; downweights large deviations. k is the cutoff: smaller k = more robust, larger k = more mean-like.",
            "SUPPORT|Harmonic and geometric are for positive data; they are blocked when a distribution can produce zero or negative values.",
        ],
        "Return to the committee question; this tab is only the exact estimator lookup.",
    ),
    "appendix_QA2": (
        "Q&A2 · Extra defense questions",
        "Presenter-only help · final backup card",
        [
            "OVERFITTING & SELECTION BIAS|• WHAT CAN THEY ASK? How do you know the GA did not simply learn the discovery data? • SIMPLE ANSWER: The search and the final evidence are separated. The GA can learn during discovery, but later the weights are frozen and cannot change. • WHAT WE DID: We used cross-validation, increasing scenario exposure, held-out checks, fresh validation seeds, stronger benchmarks, and locked-unseen related regimes. • KEY MESSAGE: Search can overfit. Frozen confirmation cannot adapt to the new evidence.",
            "FORMAL ROBUSTNESS|• WHAT CAN THEY ASK? Is the final composite formally robust? • SIMPLE ANSWER: It can be less sensitive to extreme values in practice, but that does not automatically make it formally high-breakdown robust. • IMPORTANT DETAIL: If the composite keeps positive weight on the sample mean, its influence can still be unbounded and its asymptotic breakdown point can remain zero. • KEY MESSAGE: I claim lower observed risk in selected regimes. I do not claim universal formal robustness.",
            "WEIGHT IDENTIFIABILITY|• WHAT CAN THEY ASK? Are the exact learned weights unique? • SIMPLE ANSWER: Not necessarily. Different nearby weight vectors can give almost the same risk. • HOW TO READ THE WEIGHTS: I use the weights to understand the main structure of the estimator — which estimators have more or less importance. I do not treat every decimal value as a unique scientific parameter. • KEY MESSAGE: The mixture is interpretable, but exact decimal-level weights are not claimed to be unique.",
            "LIMITATIONS|• UNIVARIATE + IID: The thesis studies one variable at a time under iid sampling. • SAMPLE SIZE: The validated range starts at n = 300, so I do not claim the same results for very small samples. • NOT COVERED: Longitudinal dependence, multivariate targets and censoring were not tested. • ESTIMATOR LIBRARY: The GA can only combine estimators included in the search library. • OPTIMIZER: This thesis tests a genetic algorithm. It does not prove that GA is the best possible optimizer compared with random search, CMA-ES, Bayesian optimization or other methods. • REAL DATA: The full-sample mean is only a reference because the true population mean is unknown. • KEY MESSAGE: The claims are limited to the conditions that were actually tested.",
            "DEPLOYMENT BOUNDARIES|• PROFILE MATCHING: A specialist should only be used when new data look similar to the profile where it was validated. • PROFILE MISMATCH: If the new data do not match the validated profile, the safe decision is to keep the benchmark. • DATA DRIFT: If the data distribution changes, the old specialist should not be trusted automatically. • PRACTICAL VALUE: A statistically positive gain is not automatically important in every real application. The useful improvement depends on the context. • KEY MESSAGE: When the evidence does not match the validated conditions, abstain and keep the benchmark.",
            "FUTURE WORK|• MORE SEARCH SEEDS: Repeat discovery with more independent GA runs. • OTHER OPTIMIZERS: Compare GA with random search, CMA-ES, Bayesian optimization or other search methods. • ABLATION: Remove estimator families one by one to see which components really matter. • PROFILE UNCERTAINTY: Build a clearer way to measure how confident we are that a new dataset matches a validated profile. • PROSPECTIVE TESTING: Take frozen specialists to completely new datasets without changing the weights. • THEORY: Study stronger mathematical bounds for when a convex mixture can improve the mean estimator.",
            "RESPONSIBLE USE & ETHICS|• DATA: The study uses simulated and public data; it is not a personal decision system. • MAIN RISK: The biggest risk is overclaiming a specialist or using it in data that do not match its validated profile. • SAFEGUARD: Benchmark retention is a form of abstention — the framework can say no when evidence is weak. • REPRODUCIBILITY: Fixed seeds, frozen weights, logged regimes and saved outputs make the process auditable. • KEY MESSAGE: The system should support a statistical decision, not replace scientific judgment.",
            "WHY GA AND NOT ANOTHER OPTIMIZER?|• SIMPLE ANSWER: GA gives a flexible way to search many valid weight combinations across generations while keeping the result interpretable. • IMPORTANT LIMIT: I did not prove that GA is the fastest or best optimizer. • DEFENSIBLE CLAIM: The contribution is the complete search-and-validation framework, not a claim that GA dominates every other optimization method.",
            "FINAL ANSWER|If I am unsure during Q&A, I return to the main rule of the thesis: the GA proposes a candidate, the weights are frozen, independent evidence decides, and the benchmark stays whenever the evidence is not strong enough.",
        ],
        "This is the last help card. Use it only if the committee asks one of these broader methodological questions.",
    )

}
