"""Accessible presenter cues for Layer 9 · Technical drill-down."""

TECHNICAL_PRESENTER_NOTES = {
    "appendix_A": (
        "Appendix A · GA mechanics",
        "Technical backup",
        [
            "INDIVIDUAL|w = one estimator recipe.",
            "C MATRIX|Fixed Monte Carlo outputs from the base estimators.",
            "EVALUATE|Every new w → Cw → loss → fitness.",
            "EVOLVE|Selection → crossover → mutation → new w → evaluate again.",
            "SIMPLEX|Weights are non-negative and sum to 1.",
            "WARM START|A previous winner may enter again, but gets no bonus.",
            "CLAIM|Fitness searches. Frozen validation decides.",
        ],
        "Open Metrics & Gate only if the committee asks how acceptance is decided.",
    ),
    "appendix_B": (
        "Appendix B · Metrics & gate",
        "Technical backup",
        [
            "TARGET|θ(F) = E[X].",
            "MSE|Average squared error.",
            "q95|Upper-tail squared error — difficult cases.",
            "GAIN|Positive gain = candidate has lower risk.",
            "GATE|ΔMSE ≥ 0 AND Δq95 ≥ 0.",
            "CI|If the interval crosses zero, replacement is uncertain.",
            "BENCHMARK|Compare against the strongest admissible benchmark.",
        ],
        "Open Technical Results only if exact candidates or numbers are requested.",
    ),
    "appendix_C": (
        "Appendix C · Technical results",
        "Technical backup",
        [
            "FIRST FUNNEL|36 → 16 → 2 confirmed.",
            "EXPANDED|26 learnable → 12 discovery winners.",
            "TAXONOMY|25 → 2 transfer · 10 local · 7 near-gate · 6 controls.",
            "SPECIALISTS|FWVR011 / FWVR012 pass locked-unseen but fail original mode.",
            "REAL DATA|26/43 eligible parents show corrected specialist wins.",
            "DEPTH|255 subgroup wins remain after correcting for many tests.",
            "AUDIT|23/34 no random pass · 8/8 strongest controls pass.",
            "CLAIM|Narrow specialists — not universal winners.",
        ],
        "Answer the exact question and stop; do not replay the full Results section.",
    ),
    "appendix_D": (
        "Appendix D · Committee Q&A",
        "Technical backup",
        [
            "WHY GA?|Search many interpretable recipes across generations.",
            "WHY AI?|Evolution can generate and improve estimator mixtures, not only select one fixed estimator.",
            "WHY q95?|Average risk can hide difficult cases.",
            "WHY FREEZE?|Prevent adaptation to confirmation data.",
            "WHY RETAIN?|The framework is allowed to say: benchmark wins.",
            "REAL DATA?|Transfer evidence — not known population truth.",
            "NOVELTY?|Integrated AI search + interpretable estimator design + frozen claim control.",
            "LIMIT?|Known truth is simulation-based; strongest gains are narrow.",
            "MAIN CONTRIBUTION|A reusable AI search framework with evidence-controlled acceptance.",
            "HYPERPARAMETERS?|Open Appendix E · Hard numbers.",
            "ESTIMATORS?|Open Appendix F · Estimator bases.",
        ],
        "Give the short answer first. Add detail only if the committee asks.",
    ),
    "appendix_E": (
        "Appendix E · Hard numbers",
        "Technical backup",
        [
            "CORE|100 candidates · 20 generations/fold · 3 folds · seeds 101/202.",
            "INIT|Dirichlet creates random valid starting weights. α=0.5 favors more uneven recipes; α=1.0 gives a neutral random spread.",
            "TOURNAMENT|Pick 2 or 3 candidates at random → compare fitness → the best becomes a parent.",
            "MUTATION|Small random change to a child's weights. Initial chance = 12% or 18%; it slowly falls toward 5%.",
            "DIVERSITY|Prevent everyone becoming too similar: keep best 1–2 + replace worst 5–10% with fresh recipes every 15 generations.",
            "STOP|Check every 5 generations. After 3 weak checks with <0.5% improvement, stop early.",
            "FITNESS|70% q95 tail risk + 30% worst scenario loss + penalties for unstable, biased or dominated recipes.",
        ],
        "Open Estimator Bases if the committee asks exactly which estimators formed each search space.",
    ),
    "appendix_F": (
        "Appendix F · Estimator bases",
        "Technical backup",
        [
            "DISCOVERY I · 10|Mean · Median · Trim20 · Harmonic · Geometric · HSM · Parzen · Trimean · Huber · Biweight.",
            "DISCOVERY II · 26|Original 10 + 16 new: Winsorized 5/10/20 · MOM 5/10/20 · Catoni .05/.10/.20/.35/.50 · Huber .75/1/1.345/1.75/2.",
            "WINSORIZED · +3|Cap the lowest/highest 5%, 10% or 20%, then average. Extremes stay, but their influence is limited.",
            "MOM · +3|Split data into 5, 10 or 20 blocks → mean each block → take the median. k = number of blocks.",
            "CATONI-TYPE · +5|Robust mean that softens large deviations. a controls how strongly that softening acts; five levels were tested.",
            "TUNED HUBER · +5|Mean-like near the centre; downweights large deviations. k is the cutoff: smaller k = more robust, larger k = more mean-like.",
            "SUPPORT|Harmonic and geometric are for positive data; they are blocked when a distribution can produce zero or negative values.",
        ],
        "Return to the committee question; this tab is only the exact estimator lookup.",
    ),

}
