"""Accessible presenter cues for Layer 6 · Thesis GA architecture and evidence pipeline."""

THESIS_GA_PRESENTER_NOTES = {
    "pipeline_architecture": (
        "Layer 6 · Thesis GA Architecture",
        "Implemented GA search-and-claim architecture",
        [
            "1 · MATRIX C|Monte Carlo outputs are stored once: rows are replications and columns are named estimators.",
            "GA CHANGES|Only the weight vector w evolves. The target θ and the evidence matrix C stay fixed.",
            "Cw|Multiply C by w to get the composite output across all replications and score the candidate quickly.",
            "2 · EVOLUTION|Create w → Cw → fitness → reproduce → new w → repeat.",
            "DIRICHLET START|Create valid starting w → Cw → fitness.",
            "SELECTION|Use fitness to choose the stronger parents.",
            "CROSSOVER|Combine two parents → create a child w.",
            "MUTATION|Nudge the child w → Cw → new fitness.",
            "DIVERSITY|Keep elites + add fresh immigrants → evaluate new w.",
            "REPEAT|New fitness scores drive the next selection.",
            "SIMPLEX|Every recipe stays valid: weights are non-negative and sum to 1.",
            "3 · SEARCH ≠ CLAIM|Fitness = 0.70 q95 + 0.30 max loss + regularisation. It ranks candidates; it does not confirm them.",
            "FREEZE|Select the promising w* and lock its weights before confirmation evidence is seen.",
            "4 · GATE|Pass only if ΔMSE ≥ 0 AND Δq95 ≥ 0. If either fails, retain the benchmark.",
            "CONFIG|N=100 · K=3 folds · G=20 generations/fold · seeds 101 and 202. The remaining settings are audit details.",
            "KEY IDEA|C stays fixed. Every new w is evaluated with Cw. Fitness guides search; frozen validation controls the claim.",
        ],
        "Next: place this GA inside the five-stage evidence pipeline.",
    ),
    "pipeline_stage_0": (
        "Layer 6 · Stage 1 — Initial Discovery",
        "Final thesis discovery sequence",
        [
            "PURPOSE|Search for promising specialists using 10 learnable estimator components.",
            "HPF1 · 60%|Start broad and expose candidates to 60% of the scenario grid.",
            "HPF2 · 80%|Give surviving signals more evidence by increasing exposure to 80%.",
            "HALVING|Concentrate computation on the most promising regimes instead of spending equally everywhere.",
            "FINALISTS|Seeds 101 and 202 search; the top 5 finalists face an internal held-out dual gate with no post-hoc retraining.",
            "STATUS|A pass here creates a discovery candidate. It is not yet the final scientific claim.",
        ],
        "Next: freeze the discovered recipe and challenge it without adaptation.",
    ),
    "pipeline_stage_1": (
        "Layer 6 · Stage 2 — Frozen Confirmation I",
        "Final thesis fixed-weight confirmation",
        [
            "FREEZE|Lock the Stage-1 weights. The GA is not rerun.",
            "STRONGER PRESSURE|The same candidate now faces 26 modern comparators.",
            "FRESH EVIDENCE|Use 8 new validation seeds plus original and locked-unseen related regimes.",
            "PRECISION|R=500 Monte Carlo replicates · B=500 paired bootstrap resamples.",
            "QUESTION|Does the exact same frozen estimator survive stronger evidence when it cannot adapt?",
            "OUTPUT|Only confirmed candidates may later enter rediscovery as protected warm starts.",
        ],
        "Next: reopen discovery with the stronger 26-estimator search basis.",
    ),
    "pipeline_stage_2": (
        "Layer 6 · Stage 3 — Expanded Rediscovery",
        "Method + fixed thesis result",
        [
            "REOPEN|10 learnable → 26 learnable. HPF1 stays 60%; HPF2 rises 80% → 90%.",
            "MODERN PRESSURE|The stronger benchmark gate is active from the beginning.",
            "WARM STARTS|CV-019 and CV-010 return because they survived Frozen I. No fitness bonus; no automatic win.",
            "CYCLE I RESULT|36 regimes → 16 discovery wins → 2 confirmed Lognormal signals.",
            "CONFIRMED|CV-019: +16.3% q95 · CV-010: +2.2% q95.",
            "CYCLE II RESULT|12 discovery winners across 5 of 6 families.",
            "FAMILY MAP|Normal 1 · Lognormal 2 · Weibull 2 · Inv. Gaussian 4 · Ex-Gaussian 0 · Ex-Wald 3.",
            "MEANING|A stronger estimator library changed where useful mixtures appeared.",
        ],
        "Next: freeze the 26-component candidates and test which signals survive strict validation.",
    ),
    "pipeline_stage_3": (
        "Layer 6 · Stage 4 — Frozen Validation II",
        "Method + fixed thesis result",
        [
            "FREEZE AGAIN|Lock the 26-component candidates. No further adaptation.",
            "TEST|Compare the same frozen weights in original + locked-unseen related regimes.",
            "TAXONOMY|25 candidates → 2 transfer · 10 local · 7 near-gate · 6 controls.",
            "TRANSFER · 2|Pass in related locked-unseen regimes.",
            "LOCAL · 10|Discovery signal, but frozen validation does not confirm transfer.",
            "NEAR-GATE · 7|Close, but not enough to replace the benchmark.",
            "CONTROLS · 6|Expected failures; benchmark correctly retained.",
            "FWVR011|Locked-unseen: +2.79% mean / +2.72% q95 · original: fail.",
            "FWVR012|Locked-unseen: +3.18% mean / +1.25% q95 · original: fail.",
            "MEANING|Two narrow Weibull transfer specialists — not family-wide winners.",
        ],
        "Next: take the frozen specialists to external data and audit benchmark retention.",
    ),
    "pipeline_stage_4": (
        "Layer 6 · Stage 5 — External Evidence + Audit",
        "Method + fixed thesis results",
        [
            "FROZEN ONLY|Use validated specialists without reoptimising on real data.",
            "FUNNEL|264 requested → 228 loaded → 120 evaluated → 43 eligible parents.",
            "BREADTH|26/43 parents had at least one corrected specialist win.",
            "MATCHED PROFILES|Test a specialist only where the real-data subgroup resembles its validated profile.",
            "DEPTH|255 subgroup wins remained after correcting for many simultaneous tests.",
            "CAUTION|255 subgroup results are not 255 independent datasets.",
            "REAL DATA|External transfer support — not known-θ population proof.",
            "AUDIT|Test 4,000 random simplex vectors × 8 seeds in benchmark-retained regimes.",
            "AUDIT RESULT|23/34 no random pass · 11/34 some signal.",
            "CONTROL|8/8 strongest positive controls passed.",
            "MEANING|External data test transfer; the random-mixture audit tests whether abstention was meaningful.",
        ],
        "Next: conclude with the smaller, evidence-controlled claim.",
    ),
}
