"""Accessible presenter cues for Layer 6 · Thesis GA architecture and evidence pipeline."""

THESIS_GA_PRESENTER_NOTES = {
    "pipeline_architecture": (
        "Layer 6 · Thesis GA Architecture",
        "Implemented GA search-and-claim architecture",
        [
            "1 · MATRIX C|Monte Carlo outputs are stored once: rows are replications and columns are named estimators.",
            "GA CHANGES|Only the weight vector w evolves. The target θ and the evidence matrix C stay fixed.",
            "Cw|Multiply C by w to get the composite output across all replications and score the candidate quickly.",
            "2 · EVOLUTION|Dirichlet start → Selection → Crossover → Mutation → Diversity → Repeat.",
            "SIMPLEX|Every recipe stays valid: weights are non-negative and sum to 1.",
            "3 · SEARCH ≠ CLAIM|Fitness = 0.70 q95 + 0.30 max loss + regularisation. It ranks candidates; it does not confirm them.",
            "FREEZE|Select the promising w* and lock its weights before confirmation evidence is seen.",
            "4 · GATE|Pass only if ΔMSE ≥ 0 AND Δq95 ≥ 0. If either fails, retain the benchmark.",
            "CONFIG|N=100 · K=3 folds · G=20 generations/fold · seeds 101 and 202. The remaining settings are audit details.",
            "KEY IDEA|Fitness guides search. Frozen validation controls the claim.",
        ],
        "Next: place this GA inside the five-stage evidence pipeline.",
    ),
    "pipeline_stage_0": (
        "Layer 6 · Stage 1 — Initial Discovery",
        "Final thesis discovery sequence",
        [
            "PURPOSE|Search for promising specialists using 10 learnable estimator components.",
            "HPF1 · 60%|Start broad and expose candidates to 60% of the scenario grid.",
            "HPF2 · 80%|Give surviving signals more evidence by increasing exposure to 80%.",
            "HALVING|Concentrate computation on the most promising regimes instead of spending equally everywhere.",
            "FINALISTS|Seeds 101 and 202 search; the top 5 finalists face an internal held-out dual gate with no post-hoc retraining.",
            "STATUS|A pass here creates a discovery candidate. It is not yet the final scientific claim.",
        ],
        "Next: freeze the discovered recipe and challenge it without adaptation.",
    ),
    "pipeline_stage_1": (
        "Layer 6 · Stage 2 — Frozen Confirmation I",
        "Final thesis fixed-weight confirmation",
        [
            "FREEZE|Lock the Stage-1 weights. The GA is not rerun.",
            "STRONGER PRESSURE|The same candidate now faces 26 modern comparators.",
            "FRESH EVIDENCE|Use 8 new validation seeds plus original and locked-unseen related regimes.",
            "PRECISION|R=500 Monte Carlo replicates · B=500 paired bootstrap resamples.",
            "QUESTION|Does the exact same frozen estimator survive stronger evidence when it cannot adapt?",
            "OUTPUT|Only confirmed candidates may later enter rediscovery as protected warm starts.",
        ],
        "Next: reopen discovery with the stronger 26-estimator search basis.",
    ),
    "pipeline_stage_2": (
        "Layer 6 · Stage 3 — Expanded Rediscovery",
        "Final thesis expanded-basis design",
        [
            "REOPEN SEARCH|All 26 estimator components are now learnable from the beginning.",
            "EXPOSURE|HPF1 stays at 60%; HPF2 increases to 90%.",
            "MODERN PRESSURE|The stronger modern benchmark gate is active from the start of rediscovery.",
            "WARM STARTS|CV-019 and CV-010 enter because they survived Frozen Confirmation I.",
            "NO BONUS|Warm starts keep their provenance but receive no fitness bonus and no automatic acceptance.",
            "QUESTION|Does the stronger 26-component basis reveal better or different specialists?",
        ],
        "Next: freeze the expanded candidates again and test how far their evidence travels.",
    ),
    "pipeline_stage_3": (
        "Layer 6 · Stage 4 — Frozen Validation II",
        "Final thesis post-discovery fixed-weight validation",
        [
            "FREEZE AGAIN|Lock the 26-component candidate weights. No further adaptation is allowed.",
            "ORIGINAL|Retest the frozen candidate in its original discovery regime.",
            "LOCKED-UNSEEN|Also test related regimes that were unavailable during discovery.",
            "EVIDENCE|Use paired bootstrap evidence and the same dual benchmark gate.",
            "TAXONOMY|Classify the outcome as transfer specialist · local evidence · near-gate · benchmark retained.",
            "QUESTION|Is the improvement transferable, only local, or unsupported?",
        ],
        "Next: take the frozen specialists outside the synthetic study and audit abstention.",
    ),
    "pipeline_stage_4": (
        "Layer 6 · Stage 5 — External Evidence + Audit",
        "Final thesis real-world battery and Dirichlet audit",
        [
            "REAL-WORLD FUNNEL|264 requested → 228 loaded → 120 evaluated → 43 eligible parent datasets.",
            "FROZEN ONLY|Apply the specialists without reoptimising their weights on real data.",
            "EXTERNAL SIGNAL|26 of 43 eligible parents had at least one corrected win; 255 profile-matched confirmations survived FDR control.",
            "REAL DATA|This is empirical calibration and transfer evidence, not known-θ population validation.",
            "DIRICHLET AUDIT|Separately test 4,000 random simplex vectors across 8 seeds in benchmark-retained regimes. This is not another GA search.",
            "AUDIT RESULT|23/34 regimes had no random pass · 11/34 showed some signal · all 8 strongest positive controls passed.",
            "KEY IDEA|External data test transfer; the random-mixture audit tests whether abstention is plausible.",
        ],
        "Next: inspect the precomputed results that survived this evidence programme.",
    ),
}
